# Generated by Django 4.2.30 on 2026-07-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_archived", "-created_at"],
                name="communicati_is_arch_452fe5_idx",
            ),
        ),
    ]
