# Generated by Django 3.2 on 2025-03-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, help_text='临时允许为空，迁移完成后将恢复非空约束', max_length=255, null=True, verbose_name='姓名'),
        ),
    ]
