# Generated by Django 3.2 on 2025-03-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20250325_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='可选字段，允许为空', max_length=254, null=True),
        ),
    ]
