"""
Django settings for omni_desk_backend project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Application version
try:
    from core.version import get_version

    APP_VERSION = get_version()
except ImportError:
    APP_VERSION = "0.0.0-dev"
BUILD_TIME = os.getenv("BUILD_TIME", "unknown")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_SECRET_KEY = os.getenv("SECRET_KEY")
if not _SECRET_KEY:
    # Phase 9: Fail loudly in production instead of silently generating random key
    # (random key would invalidate all sessions/tokens on every restart)
    if os.getenv("DJANGO_ENV") == "production" or os.getenv("DJANGO_SETTINGS_MODULE", "").endswith(".production"):
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            "Production requires SECRET_KEY environment variable. "
            "Refusing to start with a random key (would invalidate all sessions on restart)."
        )
    import warnings

    warnings.warn(
        "SECRET_KEY not set. Generating a random key for this session. "
        "This will invalidate all existing sessions on restart.",
        RuntimeWarning,
    )
    import secrets

    SECRET_KEY = secrets.token_urlsafe(50)
else:
    SECRET_KEY = _SECRET_KEY
del _SECRET_KEY

# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "personnel.apps.PersonnelConfig",
    "users",
    "events",
    "documents.apps.DocumentsConfig",
    "config",
    "memos.apps.MemosConfig",
    "dify_apps.apps.DifyAppsConfig",
    "office_assistant.apps.OfficeAssistantConfig",
    "projects",  # Add the new projects app
    "compliance",  # Add the new compliance app
    "django_celery_beat",  # Add django-celery-beat
    "ragflow_service",  # Add the new ragflow_service app
    "meeting_rooms",  # Add the new meeting_rooms app
    "sensor_management",  # Add the new sensor_management app
    "django_extensions",
    "communication",
    "news",
    "permissions.apps.PermissionsConfig",
    "ebooks.apps.EbooksConfig",
    "smart_assistant.apps.SmartAssistantConfig",
    "core.apps.CoreConfig",
    "notifications.apps.NotificationsConfig",
    "dashboard.apps.DashboardConfig",
    "external_integration.apps.ExternalIntegrationConfig",
    "django_ratelimit",
    # 文档存储代理
    "paperless_proxy",
    # 联邦搜索
    "search_federation",
    # 文件处理
    "file_processing.apps.FileProcessingConfig",
    # 联培生管理 (2026-08-19 恢复)
    "joint_students.apps.JointStudentsConfig",
]

MIDDLEWARE = [
    "core.middleware.RequestIdMiddleware",  # MUST be first
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "smart_assistant.middleware.rate_limit.RateLimitMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# For Nginx proxy with HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

ROOT_URLCONF = "omni_desk_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "omni_desk_backend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Cache (used by django-ratelimit for rate limiting)
# Uses Redis (shared with Celery) for cross-process cache
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("CACHE_REDIS_URL", "redis://localhost:6379/1"),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "zh-hans"
TIME_ZONE = "Asia/Shanghai"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# 日志配置优化
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "()": "observability.formatters.SafeTextFormatter",
            "format": "{asctime} [{levelname}] {name} [req={request_id} evt={event}]: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",  # 更改日志级别为 INFO
            "propagate": True,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# Static files
STATIC_URL = "/django-static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework配置 - 更新权限相关设置
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    # P1-8: 全局异常出口 — 5xx 强制 exc_info 日志 + 注入 request_id;4xx 只追加 request_id
    "EXCEPTION_HANDLER": "core.exception_handler.omnidesk_exception_handler",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ),
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    # 限流速率:anon 用于 IP 维度;client_error 是 core.throttles.ClientErrorAnonThrottle 的 scope,
    # 防止前端错误上报端点被错误循环/异常刷屏打爆。10/min/IP 在内网足够宽松但又能挡住滥用。
    "DEFAULT_THROTTLE_RATES": {
        "anon": "60/min",
        "client_error": "10/min",
    },
}

# JWT配置
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# CORS configuration
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "HEAD",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_EXPOSE_HEADERS = ["Content-Type", "Authorization"]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-request-source",
]

# 自定义用户模型
AUTH_USER_MODEL = "users.CustomUser"

# 权限缓存设置
PERMISSION_CACHE_TIMEOUT = 60 * 60  # 1小时

# Celery Configuration
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Shanghai"

# Celery 可靠性配置(Phase 2 优化)
CELERY_TASK_ACKS_LATE = True  # 任务完成后才确认,worker 崩溃时任务会被重新投递
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # worker 异常退出时拒绝任务(触发重试)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # 每次只预取 1 个任务,避免长任务阻塞

# Django-Celery-Beat Configuration
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

CELERY_BEAT_SCHEDULE = {
    "check-compliance-due-dates-every-day": {
        "task": "compliance.tasks.check_compliance_due_dates",
        "schedule": timedelta(days=1),  # 每天执行一次
        "args": (),
    },
    "cleanup-expired-guest-users": {
        "task": "users.tasks.cleanup_expired_guest_users",
        "schedule": timedelta(days=1),  # 每天执行一次
        "args": (),
    },
    "cleanup-calibration-reminders": {
        "task": "sensor_management.tasks.check_and_create_calibration_reminders",
        "schedule": timedelta(days=1),  # 每天执行一次(传感器校准提醒)
        "args": (),
    },
    "cleanup-expired-swap-requests": {
        "task": "events.tasks.cleanup_expired_swap_requests",
        "schedule": timedelta(hours=1),  # 每小时执行一次(换班申请过期清理,TTL 48h)
        "args": (),
    },
    "send-due-memo-reminders": {
        # P0-2:备忘录到期提醒,每分钟扫描 reminder_time 到期的未完成备忘
        "task": "memos.tasks.send_due_memo_reminders",
        "schedule": timedelta(minutes=1),
        "args": (),
    },
    "archive-expired-communication-posts": {
        # P0-6:过期帖子自动归档,每小时扫描 expires_at 到期且未归档的帖子
        "task": "communication.tasks.archive_expired_posts",
        "schedule": timedelta(hours=1),
        "args": (),
    },
    "paperless-process-outbox-every-minute": {
        "task": "paperless_proxy.process_outbox",
        "schedule": timedelta(minutes=1),
        "args": (),
    },
    "paperless-health-check-every-30s": {
        "task": "paperless_proxy.check_health",
        "schedule": timedelta(seconds=30),
        "args": (),
    },
    "paperless-cache-cleanup-every-6h": {
        "task": "paperless_proxy.cleanup_cache",
        "schedule": timedelta(hours=6),
        "args": (),
    },
    "smart-assistant-daily-digest": {
        # 智能助手每日晨报:工作日(周一~周五)8:30 巡检生成并推送
        "task": "smart_assistant.tasks.send_daily_digests",
        "schedule": crontab(hour=8, minute=30, day_of_week="1-5"),
        "args": (),
    },
}

# Mineru OCR API 配置
# 请替换为您的 Mineru API 地址和密钥
MINERU_API_URL = os.environ.get("MINERU_API_URL", "YOUR_MINERU_API_URL")
MINERU_API_KEY = os.environ.get("MINERU_API_KEY", "YOUR_MINERU_API_KEY")

# PDF 转图片工具的额外说明
# 如果您需要处理不可直接提取文本的PDF，需要安装额外的库，例如 'pdf2image'，
# 并且您的系统需要安装 Poppler。
# 例如：pip install pdf2image
# 更多信息请参考：https://pypi.org/project/pdf2image/

# Ollama 配置
OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
# 默认模型全站统一为 qwen2.5:7b（LLMRouter 兜底与 OllamaClient 均以此为回退值）
OLLAMA_MODEL_NAME = os.environ.get("OLLAMA_MODEL_NAME", "qwen2.5:7b")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# paperless 集成配置
PAPERLESS_URL = os.environ.get("PAPERLESS_URL", "http://paperless:8000")
PAPERLESS_API_TOKEN = os.environ.get("PAPERLESS_API_TOKEN", "")
PAPERLESS_TIMEOUT_SECONDS = int(os.environ.get("PAPERLESS_TIMEOUT_SECONDS", "10"))
PAPERLESS_HEALTH_CHECK_INTERVAL = int(os.environ.get("PAPERLESS_HEALTH_CHECK_INTERVAL", "30"))
PAPERLESS_HEALTH_FAILURE_THRESHOLD = int(os.environ.get("PAPERLESS_HEALTH_FAILURE_THRESHOLD", "3"))
PAPERLESS_OUTBOX_BATCH_SIZE = int(os.environ.get("PAPERLESS_OUTBOX_BATCH_SIZE", "50"))
PAPERLESS_OUTBOX_MAX_RETRIES = int(os.environ.get("PAPERLESS_OUTBOX_MAX_RETRIES", "10"))
PAPERLESS_OUTBOX_BASE_BACKOFF_SECONDS = int(os.environ.get("PAPERLESS_OUTBOX_BASE_BACKOFF_SECONDS", "30"))
PAPERLESS_CACHE_DIR = os.environ.get("PAPERLESS_CACHE_DIR", "paperless_cache/")
PAPERLESS_PENDING_DIR = os.environ.get("PAPERLESS_PENDING_DIR", "paperless_pending/")
PAPERLESS_CACHE_MAX_AGE_DAYS = int(os.environ.get("PAPERLESS_CACHE_MAX_AGE_DAYS", "30"))
PAPERLESS_CLEANUP_INTERVAL_HOURS = int(os.environ.get("PAPERLESS_CLEANUP_INTERVAL_HOURS", "6"))

# Smart Assistant 缓存版本(部署级;工具升级时 bump 此值即可失效旧缓存)
SMART_ASSISTANT_CACHE_VERSION = os.environ.get("SMART_ASSISTANT_CACHE_VERSION", "1.0")

# === L1 原生 Function Calling(2026-08-06)===
# 路由开关:True 走原生 tool_calls 协议,False 保留 JSON 路径。
# 端点级能力:LlmEndpoint.model_capabilities.native_tool_calls=False 时即使本开关为 True
# 也自动降级到 JSON 路径,保证旧端点安全兼容。
USE_NATIVE_TOOL_CALLS = os.environ.get("USE_NATIVE_TOOL_CALLS", "true").lower() in ("1", "true", "yes")
# 单次 agent 调用的 tool_calls 最大轮数(防无限循环 / 死循环调工具)
MAX_TOOL_CALLS_ROUNDS = int(os.environ.get("MAX_TOOL_CALLS_ROUNDS", "3"))
# 单次工具调用的超时(秒),超时则注入 tool_error 让 LLM 重选
TOOL_CALLS_TIMEOUT_SECONDS = int(os.environ.get("TOOL_CALLS_TIMEOUT_SECONDS", "30"))
# L1 灰度(Task 12):默认仅 is_staff=True 用户启用原生 tool_calls 路径,
# 非 staff 用户自动降级到 JSON 路径。验证 1 周后置 True 全员开放。
USE_NATIVE_TOOL_CALLS_FOR_ALL = os.environ.get("USE_NATIVE_TOOL_CALLS_FOR_ALL", "false").lower() in ("1", "true", "yes")

# === 联培生管理 (2026-08-19 恢复) ===
# 每月几号 02:00 触发考核批次自动创建任务 (Celery Beat cron)
JOINT_STUDENT_CYCLE_DAY = int(os.environ.get("JOINT_STUDENT_CYCLE_DAY", "25"))
