# Generated by Django 5.1.3 on 2025-04-01 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('tech_design', '技术方案文档'), ('test_case', '测试用例文档'), ('meeting_minutes', '会议纪要'), ('progress_report', '项目进度报告')], max_length=50, verbose_name='模板类型')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('variables', models.JSONField(default=dict, verbose_name='模板变量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '文档模板',
                'verbose_name_plural': '文档模板',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='生成内容')),
                ('variables_used', models.JSONField(default=dict, verbose_name='使用变量')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('is_final', models.BooleanField(default=False, verbose_name='最终版本')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生成用户')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttemplate', verbose_name='关联模板')),
            ],
            options={
                'verbose_name': '生成文档',
                'verbose_name_plural': '生成文档',
                'ordering': ['-generated_at'],
            },
        ),
    ]
