# Generated by Django 5.1.3 on 2025-08-12 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_chapter_heading_structure_chapter_image_metadata'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_in_project', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates_in_project', to='projects.project', verbose_name='所属项目'),
        ),
    ]
