# Generated by Django 4.2.11 on 2026-01-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifyApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='应用名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='应用描述')),
                ('embed_url', models.URLField(max_length=500, verbose_name='嵌入式 URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Dify 应用',
                'verbose_name_plural': 'Dify 应用',
                'ordering': ['name'],
            },
        ),
    ]
