# Generated by Django 4.2.11 on 2026-06-21 07:02

from django.db import migrations
import personnel.models


class Migration(migrations.Migration):

    dependencies = [
        ("external_integration", "0003_plugin_pluginversion_plugincalllog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationservice",
            name="api_key",
            field=personnel.models.EncryptedCharField(
                blank=True, default="", max_length=255, verbose_name="API 密钥"
            ),
        ),
    ]
