# Generated by Django 4.2.11 on 2026-06-05 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0002_alter_notification_is_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(blank=True, null=True, verbose_name="免打扰开始"),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(blank=True, null=True, verbose_name="免打扰结束"),
                ),
                (
                    "channel_settings",
                    models.JSONField(blank=True, default=dict, verbose_name="渠道设置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "通知偏好",
                "verbose_name_plural": "通知偏好管理",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="dedupe_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, verbose_name="去重键"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "低"), (2, "普通"), (3, "高"), (4, "紧急")],
                default=2,
                verbose_name="优先级",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="已读时间"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("schedule_change", "排班变更"),
                    ("announcement", "公告发布"),
                    ("memo_due", "备忘录到期"),
                    ("calibration_reminder", "校准提醒"),
                    ("project_update", "项目更新"),
                    ("compliance_issue", "合规问题"),
                    ("system", "系统通知"),
                    ("position_changed", "岗位/部门变动"),
                    ("account_linked", "账号已关联"),
                    ("emergency_contact", "紧急联系人变更"),
                    ("training_assigned", "培训任务分配"),
                    ("reward_punishment", "奖惩记录"),
                ],
                max_length=30,
                verbose_name="通知类型",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"], name="notif_user_read_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["dedupe_key", "created_at"], name="notif_dedupe_idx"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_pref",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
