# Generated by Django 4.2.11 on 2026-06-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0003_notificationpreference_notification_dedupe_key_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("schedule_change", "排班变更"),
                    ("announcement", "公告发布"),
                    ("memo_due", "备忘录到期"),
                    ("calibration_reminder", "校准提醒"),
                    ("project_update", "项目更新"),
                    ("compliance_issue", "合规问题"),
                    ("system", "系统通知"),
                    ("position_changed", "岗位/部门变动"),
                    ("account_linked", "账号已关联"),
                    ("emergency_contact", "紧急联系人变更"),
                    ("training_assigned", "培训任务分配"),
                    ("reward_punishment", "奖惩记录"),
                    ("schedule_swap_requested", "换班申请已发起"),
                    ("schedule_swap_approved", "换班已生效(双方互认)"),
                    ("schedule_swap_rejected", "换班被接收方拒绝"),
                    ("schedule_swap_cancelled", "换班已撤销"),
                    ("schedule_swap_expired", "换班申请已超时"),
                ],
                max_length=30,
                verbose_name="通知类型",
            ),
        ),
    ]
