# Generated by Django 4.2.30 on 2026-08-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('schedule_change', '排班变更'), ('announcement', '公告发布'), ('memo_due', '备忘录到期'), ('calibration_reminder', '校准提醒'), ('project_update', '项目更新'), ('compliance_issue', '合规问题'), ('system', '系统通知'), ('position_changed', '岗位/部门变动'), ('account_linked', '账号已关联'), ('emergency_contact', '紧急联系人变更'), ('training_assigned', '培训任务分配'), ('reward_punishment', '奖惩记录'), ('schedule_swap_requested', '换班申请已发起'), ('schedule_swap_approved', '换班已生效(双方互认)'), ('schedule_swap_rejected', '换班被接收方拒绝'), ('schedule_swap_cancelled', '换班已撤销'), ('schedule_swap_expired', '换班申请已超时'), ('paperless_down', 'Paperless 服务不可用'), ('paperless_recovered', 'Paperless 服务已恢复'), ('compliance_due', '合规问题到期'), ('agent_notify', '智能助手通知'), ('agent_task_result', '智能助手任务结果')], db_index=True, max_length=30, verbose_name='通知类型'),
        ),
    ]
