# Generated by Django 4.2.30 on 2026-08-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_alter_notification_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("type", "agent_task_result"),
                    models.Q(("dedupe_key", ""), _negated=True),
                ),
                fields=("user", "type", "dedupe_key"),
                name="notif_agent_task_dedupe_uniq",
            ),
        ),
    ]
