# Generated by Django 5.1.3 on 2025-08-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, verbose_name='页面名称')),
                ('page_path', models.CharField(max_length=200, unique=True, verbose_name='页面路径')),
                ('is_hidden_for_non_admin', models.BooleanField(default=False, verbose_name='对非管理员隐藏')),
            ],
            options={
                'verbose_name': '页面配置',
                'verbose_name_plural': '页面配置',
            },
        ),
    ]
