# Generated by Django 5.1.3 on 2025-08-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_pageconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True, verbose_name='配置别名')),
                ('api_endpoint', models.URLField(verbose_name='API 地址')),
                ('model', models.CharField(max_length=100, verbose_name='模型名称')),
                ('temperature', models.FloatField(blank=True, default=0.8, null=True, verbose_name='Temperature')),
                ('top_p', models.FloatField(blank=True, default=0.9, null=True, verbose_name='Top P')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Ollama 配置',
                'verbose_name_plural': 'Ollama 配置',
            },
        ),
    ]
