# Generated by Django 5.1.3 on 2025-11-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('config', '0003_ollamaconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='显示名称')),
                ('path', models.CharField(max_length=255, unique=True, verbose_name='路由路径')),
            ],
            options={
                'verbose_name': '页面',
                'verbose_name_plural': '页面',
            },
        ),
        migrations.CreateModel(
            name='PageVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.page')),
            ],
            options={
                'verbose_name': '页面可见性',
                'verbose_name_plural': '页面可见性',
                'unique_together': {('page', 'group')},
            },
        ),
    ]
