# Generated by Django 4.2.11 on 2026-01-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='页面名称')),
                ('path', models.CharField(max_length=255, unique=True, verbose_name='路由路径')),
                ('component', models.CharField(max_length=255, verbose_name='前端组件')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='permissions.pageroute', verbose_name='父级页面')),
            ],
            options={
                'verbose_name': '页面路由',
                'verbose_name_plural': '页面路由',
            },
        ),
        migrations.CreateModel(
            name='GroupPagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='用户组')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.pageroute', verbose_name='页面')),
            ],
            options={
                'verbose_name': '用户组页面权限',
                'verbose_name_plural': '用户组页面权限',
                'unique_together': {('group', 'page')},
            },
        ),
    ]
