# Generated by Django 4.2.11 on 2025-12-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='传感器名称')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='传感器编号')),
                ('calibration_range', models.CharField(max_length=255, verbose_name='校准范围')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_temperature', models.FloatField(verbose_name='室温 (℃)')),
                ('relative_humidity', models.FloatField(verbose_name='相对湿度 (%RH)')),
                ('calibration_instrument', models.CharField(max_length=255, verbose_name='校准用仪器')),
                ('calibration_date', models.DateField(verbose_name='校准日期')),
                ('main_table_data', models.JSONField(default=dict, verbose_name='主要表格数据')),
                ('performance_indicators', models.JSONField(default=dict, verbose_name='性能指标')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_records', to='sensors.sensor', verbose_name='传感器')),
            ],
        ),
    ]
