# Generated by Django 4.2.30 on 2026-07-08 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("project_document", "项目文档"),
                            ("contract", "合同"),
                            ("policy", "制度文件"),
                            ("compliance_report", "合规检查报告"),
                            ("personnel_file", "人事档案"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="业务源类型",
                    ),
                ),
                (
                    "source_id",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="业务源 ID"
                    ),
                ),
                (
                    "paperless_id",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="paperless 文档 ID"
                    ),
                ),
                (
                    "paperless_checksum",
                    models.CharField(max_length=64, verbose_name="paperless 校验和"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="文档标题")),
                (
                    "correspondent_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="paperless correspondent ID"
                    ),
                ),
                (
                    "extra_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="扩展元数据"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paperless_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档绑定",
                "verbose_name_plural": "文档绑定",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="paperless_p_source__033894_idx",
                    ),
                    models.Index(
                        fields=["owner", "source_type"],
                        name="paperless_p_owner_i_0007da_idx",
                    ),
                ],
                "unique_together": {("source_type", "source_id")},
            },
        ),
    ]
