# Generated by Django 4.2.30 on 2026-07-08 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paperless_proxy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("upload", "上传"),
                            ("update_metadata", "更新元数据"),
                            ("delete", "删除"),
                        ],
                        max_length=32,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待同步"),
                            ("syncing", "同步中"),
                            ("synced", "已同步"),
                            ("failed", "失败(可重试)"),
                            ("dead", "死信(需人工)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="操作载荷")),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="已重试次数"),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=10, verbose_name="最大重试次数"
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="下次重试时间",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="最后错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox",
                        to="paperless_proxy.documentbinding",
                        verbose_name="关联绑定",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paperless_outbox",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbox 项",
                "verbose_name_plural": "Outbox 项",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="paperless_p_status_458c06_idx",
                    )
                ],
            },
        ),
    ]
