# Generated by Django 4.2.30 on 2026-07-08 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paperless_proxy", "0002_outboxitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPaperlessBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paperless_user_id",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="paperless 用户 ID"
                    ),
                ),
                (
                    "paperless_username",
                    models.CharField(max_length=150, verbose_name="paperless 用户名"),
                ),
                (
                    "bound_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="绑定时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paperless_bind",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OmniDesk 用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "paperless 账号绑定",
                "verbose_name_plural": "paperless 账号绑定",
            },
        ),
    ]
