# Generated by Django 4.2.30 on 2026-07-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paperless_proxy", "0003_userpaperlessbinding"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperlessHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_healthy",
                    models.BooleanField(default=True, verbose_name="是否健康"),
                ),
                (
                    "last_check_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后检查时间"),
                ),
                (
                    "consecutive_failures",
                    models.PositiveIntegerField(default=0, verbose_name="连续失败次数"),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="最后错误")),
            ],
            options={
                "verbose_name": "paperless 健康状态",
                "verbose_name_plural": "paperless 健康状态",
            },
        ),
    ]
