# Generated by Django 4.2.30 on 2026-07-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paperless_proxy", "0004_paperlesshealth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentbinding",
            name="paperless_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="paperless 文档 ID"
            ),
        ),
    ]
