# Generated by Django 4.2.30 on 2026-05-02 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartAssistantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '助手会话',
                'verbose_name_plural': '助手会话',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文档标题')),
                ('file', models.FileField(upload_to='knowledge_base/', verbose_name='文档文件')),
                ('content_text', models.TextField(blank=True, verbose_name='提取的文本内容')),
                ('embedding_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('ragflow_document_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ragflow 文档ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '知识库文档',
                'verbose_name_plural': '知识库文档',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(verbose_name='用户问题')),
                ('intent', models.CharField(max_length=50, verbose_name='识别的意图类型')),
                ('tool_used', models.CharField(max_length=50, verbose_name='使用的工具')),
                ('tool_input', models.JSONField(default=dict, verbose_name='工具输入')),
                ('tool_output', models.JSONField(default=dict, verbose_name='工具输出')),
                ('llm_response', models.TextField(verbose_name='LLM 回答')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_assistant.smartassistantsession')),
            ],
            options={
                'verbose_name': 'Agent 日志',
                'verbose_name_plural': 'Agent 日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
