# Generated by Django 4.2.30 on 2026-05-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartassistantsession",
            name="messages",
            field=models.JSONField(default=list, verbose_name="对话消息历史"),
        ),
    ]
