# Generated by Django 4.2.30 on 2026-05-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_assistant', '0002_smartassistantsession_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('api_endpoint', models.URLField(verbose_name='API 端点')),
                ('api_key', models.CharField(max_length=500, verbose_name='API 密钥')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('temperature', models.FloatField(blank=True, default=0.7, null=True)),
                ('top_p', models.FloatField(blank=True, default=0.9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM 配置',
                'verbose_name_plural': 'LLM 配置',
                'ordering': ['-created_at'],
            },
        ),
    ]
