# Generated by Django 4.2.11 on 2026-06-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_assistant", "0005_add_document_category_and_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentlog",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=10,
                null=True,
                verbose_name="预估费用（元）",
            ),
        ),
        migrations.AddField(
            model_name="agentlog",
            name="input_tokens",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="输入 token 数"
            ),
        ),
        migrations.AddField(
            model_name="agentlog",
            name="model_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="使用的模型"
            ),
        ),
        migrations.AddField(
            model_name="agentlog",
            name="output_tokens",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="输出 token 数"
            ),
        ),
        migrations.AddField(
            model_name="agentlog",
            name="response_time_ms",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="响应时间（ms）"
            ),
        ),
        migrations.AddField(
            model_name="agentlog",
            name="tool_success",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="工具执行是否成功"
            ),
        ),
        migrations.AddField(
            model_name="agentlog",
            name="total_tokens",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="总 token 数"
            ),
        ),
        migrations.AddField(
            model_name="agentlog",
            name="user_feedback",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="用户反馈（up/down）",
            ),
        ),
        migrations.AddField(
            model_name="llmendpoint",
            name="cost_per_1k_tokens",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=10,
                null=True,
                verbose_name="每千 token 费用（元）",
            ),
        ),
        migrations.AddField(
            model_name="llmendpoint",
            name="is_fallback",
            field=models.BooleanField(default=False, verbose_name="是否为备用端点"),
        ),
        migrations.AddField(
            model_name="llmendpoint",
            name="model_capabilities",
            field=models.JSONField(blank=True, default=list, verbose_name="模型能力"),
        ),
        migrations.AddField(
            model_name="llmendpoint",
            name="priority",
            field=models.IntegerField(
                default=1, verbose_name="优先级（数字越小优先级越高）"
            ),
        ),
        migrations.AddField(
            model_name="smartassistantsession",
            name="summary_text",
            field=models.TextField(blank=True, default="", verbose_name="早期对话摘要"),
        ),
        migrations.AddField(
            model_name="smartassistantsession",
            name="summary_token_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="摘要 token 数"
            ),
        ),
        migrations.AddField(
            model_name="smartassistantsession",
            name="turn_count",
            field=models.IntegerField(default=0, verbose_name="对话轮数"),
        ),
    ]
