# Generated by Django 4.2.30 on 2026-06-21 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("smart_assistant", "0007_add_knowledge_dataset_and_doc_dataset_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.UUIDField(
                        editable=False, unique=True, verbose_name="任务 ID"
                    ),
                ),
                ("objective", models.TextField(verbose_name="任务目标")),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("pipeline", "顺序执行"),
                            ("fanout", "并行执行"),
                            ("hierarchical", "层级执行"),
                        ],
                        default="pipeline",
                        max_length=20,
                        verbose_name="执行模式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("paused", "已暂停"),
                            ("completed", "已完成"),
                            ("failed", "已失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "task_packet",
                    models.JSONField(
                        default=dict, verbose_name="任务包(Supervisor 生成的 JSON)"
                    ),
                ),
                (
                    "global_budget",
                    models.IntegerField(default=20000, verbose_name="全局 Token 预算"),
                ),
                (
                    "tokens_used",
                    models.IntegerField(default=0, verbose_name="已使用 Token 数"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "final_output",
                    models.JSONField(blank=True, null=True, verbose_name="最终产出物"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_tasks",
                        to="smart_assistant.smartassistantsession",
                        verbose_name="关联会话",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起人",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 任务",
                "verbose_name_plural": "Agent 任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentSubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtask_id",
                    models.CharField(
                        max_length=64, verbose_name="子任务 ID(在 TaskPacket 中唯一)"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        max_length=30, verbose_name="执行角色(AgentRole 枚举值)"
                    ),
                ),
                ("objective", models.TextField(verbose_name="子任务目标")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "已失败"),
                            ("skipped", "已跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="子任务状态",
                    ),
                ),
                (
                    "depends_on",
                    models.JSONField(
                        blank=True, default=list, verbose_name="依赖的子任务 ID 列表"
                    ),
                ),
                (
                    "inputs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="输入参数(支持 $task_id.field 引用)",
                    ),
                ),
                (
                    "output",
                    models.JSONField(blank=True, null=True, verbose_name="产出物"),
                ),
                (
                    "tokens_used",
                    models.IntegerField(default=0, verbose_name="已使用 Token 数"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="smart_assistant.agenttask",
                        verbose_name="所属主任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 子任务",
                "verbose_name_plural": "Agent 子任务",
                "ordering": ["task", "subtask_id"],
                "unique_together": {("task", "subtask_id")},
            },
        ),
        migrations.CreateModel(
            name="AgentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(verbose_name="事件序号(任务内递增)"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("task.started", "任务开始"),
                            ("task.paused", "任务暂停(等待用户介入)"),
                            ("task.resumed", "任务恢复"),
                            ("task.completed", "任务完成"),
                            ("task.failed", "任务失败"),
                            ("task.cancelled", "任务取消"),
                            ("subtask.started", "子任务开始"),
                            ("subtask.progress", "子任务进度(LLM 流式输出)"),
                            ("subtask.tool_call", "子任务工具调用"),
                            ("subtask.quality_gate", "子任务质量门禁检查"),
                            ("subtask.completed", "子任务完成"),
                            ("subtask.failed", "子任务失败"),
                            ("supervisor.decision", "Supervisor 决策"),
                            ("supervisor.intervention", "Supervisor 介入"),
                            ("user.intervention", "用户介入"),
                            ("hook.triggered", "Hook 触发"),
                        ],
                        max_length=40,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="事件详细数据"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="事件时间"),
                ),
                (
                    "subtask",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="smart_assistant.agentsubtask",
                        verbose_name="关联子任务",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="smart_assistant.agenttask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 事件",
                "verbose_name_plural": "Agent 事件",
                "ordering": ["task", "sequence"],
                "unique_together": {("task", "sequence")},
            },
        ),
    ]
