# Generated by Django 4.2.11 on 2026-06-21 07:02

from django.db import migrations
import personnel.models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_assistant", "0008_add_multi_agent_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmendpoint",
            name="api_key",
            field=personnel.models.EncryptedCharField(
                max_length=500, verbose_name="API 密钥"
            ),
        ),
    ]
