# Generated by Django 4.2.30 on 2026-07-17 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_assistant', '0010_smart_assistant_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolChainPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('current_step', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_chain_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'smart_assistant_tool_chain_plan',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='smart_assis_user_id_bd3ef8_idx'), models.Index(fields=['created_at'], name='smart_assis_created_c60797_idx')],
            },
        ),
    ]
