# Generated by Django 4.2.30 on 2026-07-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_assistant", "0011_toolchainplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartassistantsession",
            name="last_error",
            field=models.TextField(blank=True, default="", verbose_name="最近错误"),
        ),
    ]
