# Generated by Django 4.2.30 on 2026-07-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_assistant", "0012_smartassistantsession_last_error"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(
                fields=["user", "-created_at"], name="smart_assis_user_id_473038_idx"
            ),
        ),
    ]
