# Generated by Django 4.2.30 on 2026-08-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_assistant", "0013_agenttask_smart_assis_user_id_473038_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentlog",
            name="tool_call_path",
            field=models.CharField(
                blank=True,
                choices=[("native", "native"), ("json", "json"), ("none", "none")],
                default="none",
                max_length=16,
                verbose_name="工具调用路径",
            ),
        ),
        migrations.AddField(
            model_name="agentlog",
            name="tool_calls_meta",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="每轮工具调用的元数据(rounds/tool/arguments/duration_ms)",
            ),
        ),
        migrations.AddField(
            model_name="agentlog",
            name="tool_calls_rounds",
            field=models.IntegerField(
                default=0, verbose_name="实际工具调用轮数(用于审计 / 成本分析)"
            ),
        ),
    ]
