# Generated by Django 4.2.30 on 2026-08-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_assistant", "0014_native_function_calling"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmappconfig",
            name="app_name",
            field=models.CharField(
                choices=[
                    ("smart_assistant", "智能助手"),
                    ("office_assistant", "办公助手"),
                ],
                max_length=50,
                verbose_name="应用名称",
            ),
        ),
    ]
