# Generated by Django 4.2.30 on 2026-08-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smart_assistant", "0015_add_office_assistant_app_choice"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="agentevent",
            index=models.Index(fields=["task", "-sequence"], name="smart_assis_task_id_84bc7c_idx"),
        ),
        migrations.AddIndex(
            model_name="agentlog",
            index=models.Index(fields=["-created_at"], name="smart_assis_created_e0c338_idx"),
        ),
        migrations.AddIndex(
            model_name="agentlog",
            index=models.Index(fields=["intent"], name="smart_assis_intent_365c23_idx"),
        ),
    ]
