# Generated by Django 4.2.30 on 2026-08-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_assistant', '0016_agentevent_smart_assis_task_id_84bc7c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentevent',
            name='event_type',
            field=models.CharField(choices=[('task.started', '任务开始'), ('task.paused', '任务暂停(等待用户介入)'), ('task.resumed', '任务恢复'), ('task.completed', '任务完成'), ('task.failed', '任务失败'), ('task.cancelled', '任务取消'), ('subtask.started', '子任务开始'), ('subtask.progress', '子任务进度(LLM 流式输出)'), ('subtask.tool_call', '子任务工具调用'), ('subtask.quality_gate', '子任务质量门禁检查'), ('subtask.completed', '子任务完成'), ('subtask.failed', '子任务失败'), ('subtask.skipped', '子任务跳过'), ('subtask.tool_result', '子任务工具结果'), ('task.aborted', '任务中止'), ('supervisor.decision', 'Supervisor 决策'), ('supervisor.intervention', 'Supervisor 介入'), ('user.intervention', '用户介入'), ('hook.triggered', 'Hook 触发')], max_length=40, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '已失败'), ('partial', '部分完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态'),
        ),
    ]
