# Generated by Django 4.2.30 on 2026-09-28 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("smart_assistant", "0019_agenttask_resume_claim_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(unique=True, verbose_name="角色标识")),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("description", models.TextField(blank=True, verbose_name="职责说明")),
                ("system_prompt", models.TextField(blank=True, verbose_name="系统提示词")),
                ("toolsets", models.JSONField(blank=True, default=list, verbose_name="工具集白名单")),
                ("data_scope", models.CharField(blank=True, max_length=200, verbose_name="数据范围说明")),
                (
                    "trigger",
                    models.CharField(
                        choices=[("passive", "被动"), ("beat", "定时"), ("event", "业务事件")],
                        default="beat",
                        max_length=20,
                        verbose_name="触发方式",
                    ),
                ),
                ("schedule_label", models.CharField(blank=True, max_length=100, verbose_name="定时说明")),
                ("enabled", models.BooleanField(default=False, verbose_name="是否启用")),
                ("daily_llm_quota", models.PositiveIntegerField(default=0, verbose_name="每日 LLM 调用配额")),
                ("daily_action_quota", models.PositiveIntegerField(default=100, verbose_name="每日动作配额")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_agent_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责人",
                    ),
                ),
            ],
            options={
                "verbose_name": "数字员工",
                "verbose_name_plural": "数字员工",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "trigger",
                    models.CharField(choices=[("beat", "定时"), ("manual", "手动")], default="beat", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("succeeded", "成功"),
                            ("degraded", "已降级"),
                            ("failed", "失败"),
                            ("skipped", "已跳过"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("error", models.CharField(blank=True, max_length=500)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="smart_assistant.agentprofile",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AgentProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("fields", models.JSONField(blank=True, default=dict)),
                ("preview", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待确认"),
                            ("approved", "已确认"),
                            ("rejected", "已取消"),
                            ("expired", "已过期"),
                            ("failed", "执行失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("dedupe_key", models.CharField(max_length=200)),
                ("expires_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="smart_assistant.agentprofile",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="smart_assistant.agentrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AgentRunEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("run.started", "运行开始"),
                            ("run.completed", "运行完成"),
                            ("run.failed", "运行失败"),
                            ("run.skipped", "运行跳过"),
                            ("llm.call", "调用 LLM"),
                            ("llm.fallback", "LLM 降级"),
                            ("notify.sent", "发送通知"),
                            ("proposal.created", "创建待确认事项"),
                            ("proposal.approved", "待确认事项已确认"),
                            ("proposal.rejected", "待确认事项已取消"),
                            ("proposal.expired", "待确认事项已过期"),
                            ("proposal.failed", "待确认事项执行失败"),
                            ("quota.exceeded", "超出配额"),
                            ("config.changed", "配置变更"),
                        ],
                        max_length=40,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="smart_assistant.agentprofile",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="smart_assistant.agentrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["profile", "event_type", "created_at"], name="smart_assis_profile_b0fae5_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(fields=["profile", "-started_at"], name="smart_assis_profile_cdb5e5_idx"),
        ),
        migrations.AddIndex(
            model_name="agentproposal",
            index=models.Index(fields=["user", "status", "-created_at"], name="smart_assis_user_id_f4b61d_idx"),
        ),
        migrations.AddConstraint(
            model_name="agentproposal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("user", "dedupe_key"),
                name="uniq_pending_agent_proposal",
            ),
        ),
    ]
