# Generated by Django 4.2.30 on 2026-09-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_assistant', '0021_seed_agent_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('announcement', '公告'), ('paperless_document', '文档库')], max_length=32, verbose_name='来源类型')),
                ('source_id', models.PositiveIntegerField(verbose_name='来源对象 ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='标题')),
                ('ragflow_dataset_id', models.CharField(blank=True, default='', max_length=100, verbose_name='RAGFlow 数据集 ID')),
                ('ragflow_document_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='RAGFlow 文档 ID')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='入库内容 sha256')),
                ('status', models.CharField(choices=[('pending', '待入库'), ('ingested', '已入库'), ('failed', '失败'), ('removed', '已移除')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='连续失败次数')),
                ('last_error', models.CharField(blank=True, default='', max_length=500, verbose_name='最近错误')),
                ('ingested_at', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '知识入库记录',
                'verbose_name_plural': '知识入库记录',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='uniq_knowledge_source'),
        ),
    ]
