# Generated by Django 4.2.30 on 2026-09-28 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("smart_assistant", "0022_knowledge_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="LlmBudgetPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "scope",
                    models.CharField(
                        choices=[("default", "全员默认"), ("group", "用户组"), ("user", "个人"), ("app", "应用")],
                        max_length=16,
                        verbose_name="作用范围",
                    ),
                ),
                ("app_name", models.CharField(blank=True, default="", max_length=50, verbose_name="应用")),
                (
                    "daily_token_limit",
                    models.PositiveBigIntegerField(default=0, verbose_name="每日 token 上限（0 不限）"),
                ),
                ("daily_call_limit", models.PositiveIntegerField(default=0, verbose_name="每日调用次数上限（0 不限）")),
                ("soft_limit_percent", models.PositiveSmallIntegerField(default=80, verbose_name="只读阈值（%）")),
                ("note", models.CharField(blank=True, default="", max_length=200, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="auth.group",
                        verbose_name="用户组",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_budget_policies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM 预算上限",
                "verbose_name_plural": "LLM 预算上限",
                "ordering": ["scope", "id"],
            },
        ),
        migrations.CreateModel(
            name="LlmUsageDaily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="日期")),
                ("user_key", models.PositiveIntegerField(default=0, editable=False)),
                ("app_name", models.CharField(max_length=50, verbose_name="应用")),
                ("staff_key", models.CharField(blank=True, default="", max_length=32, verbose_name="数字员工")),
                ("calls", models.PositiveIntegerField(default=0, verbose_name="成功调用次数")),
                ("failed_calls", models.PositiveIntegerField(default=0, verbose_name="失败调用次数")),
                ("estimated_calls", models.PositiveIntegerField(default=0, verbose_name="估算 token 的调用次数")),
                ("prompt_tokens", models.PositiveBigIntegerField(default=0)),
                ("completion_tokens", models.PositiveBigIntegerField(default=0)),
                ("total_tokens", models.PositiveBigIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=14, verbose_name="预估费用"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_usage_days",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM 每日用量",
                "verbose_name_plural": "LLM 每日用量",
                "indexes": [
                    models.Index(fields=["date", "app_name"], name="llm_usage_date_app"),
                    models.Index(fields=["user", "date"], name="llm_usage_user_date"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="llmusagedaily",
            constraint=models.UniqueConstraint(
                fields=("date", "user_key", "app_name", "staff_key"), name="uniq_llm_usage_daily"
            ),
        ),
        migrations.AddConstraint(
            model_name="llmbudgetpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "default")), fields=("scope",), name="uniq_llm_budget_default"
            ),
        ),
        migrations.AddConstraint(
            model_name="llmbudgetpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "group")), fields=("group",), name="uniq_llm_budget_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="llmbudgetpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "user")), fields=("user",), name="uniq_llm_budget_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="llmbudgetpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "app")), fields=("app_name",), name="uniq_llm_budget_app"
            ),
        ),
    ]
