# Generated by Django 4.2.11 on 2026-01-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('reminder_time', models.DateTimeField(blank=True, null=True, verbose_name='提醒时间')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '备忘录',
                'verbose_name_plural': '备忘录管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
