# Generated by Django 4.2.30 on 2026-05-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='reminder_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='提醒时间'),
        ),
    ]
