# Generated by Django 4.2.30 on 2026-08-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0003_alter_memo_is_completed_alter_memo_reminder_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="reminder_sent",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="P0-2:定时任务发送到期提醒后置 True,防止 beat 重复执行时重复提醒",
                verbose_name="到期提醒已发送",
            ),
        ),
    ]
