# Generated by Django 4.2.30 on 2026-08-09 15:27

from django.db import migrations, models
from django.utils import timezone


def backfill_reminder_sent(apps, schema_editor):
    """存量已过期备忘回填 reminder_sent=True,防首次部署"补发提醒风暴"(评审 M-3)。

    升级后若不加回填,所有历史 reminder_time<=now 且未完成的备忘会在首次 beat
    运行时一次性全部触发提醒——这些备忘的到期时刻早已过去,补发噪音大。此处把
    部署时刻前已到期的备忘标记为"已提醒",新备忘不受影响。
    """
    Memo = apps.get_model("memos", "Memo")
    Memo.objects.filter(reminder_time__isnull=False, reminder_time__lte=timezone.now()).update(reminder_sent=True)


def noop_reverse(apps, schema_editor):
    """回滚不做数据还原(删除字段即回退)。"""


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0003_alter_memo_is_completed_alter_memo_reminder_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="reminder_sent",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="P0-2:定时任务发送到期提醒后置 True,防止 beat 重复执行时重复提醒",
                verbose_name="到期提醒已发送",
            ),
        ),
        migrations.RunPython(backfill_reminder_sent, noop_reverse),
    ]
