# Generated by Django 4.2.30 on 2026-08-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0004_memo_reminder_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="memo",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="是否已删除"
            ),
        ),
    ]
