[pytest]
DJANGO_SETTINGS_MODULE = omni_desk_backend.settings.test
python_files = tests.py test_*.py *_tests.py

# Coverage
addopts = --cov=. --cov-report=term-missing --cov-report=html --cov-report=xml --cov-fail-under=80
filterwarnings =
    ignore::DeprecationWarning