version: '3.8'

services:
  frontend:
    image: ${DOCKER_USER}/calendar-frontend:${FRONTEND_VERSION}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DEBUG=False
      - REACT_APP_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: ${DOCKER_USER}/calendar-backend:${BACKEND_VERSION}
    command: bash -c "python manage.py migrate && python -m waitress --port=8000 DRFForVue.wsgi:application"
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=production
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=!@#django-insecure-9g_8=0q^fz$3k&9m6v%_wx@7t6r4b5y_u*8h7=+!k
      - DJANGO_SETTINGS_MODULE=DRFForVue.settings
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
