# Generated by Django 4.2.30 on 2026-07-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("进行中", "进行中"),
                    ("已完成", "已完成"),
                    ("已暂停", "已暂停"),
                    ("已取消", "已取消"),
                ],
                db_index=True,
                default="进行中",
                max_length=50,
                verbose_name="项目状态",
            ),
        ),
    ]
