# Generated by Django 4.2.30 on 2026-08-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="更新时间"
            ),
        ),
    ]
