# Generated by Django 4.2.30 on 2026-04-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="书名")),
                (
                    "author",
                    models.CharField(blank=True, max_length=100, verbose_name="作者"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="ebooks/", verbose_name="文件"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "电子书",
                "verbose_name_plural": "电子书",
                "ordering": ["-created_at"],
            },
        ),
    ]
