# Generated by Django 5.1.3 on 2025-08-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RagflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='配置名称')),
                ('api_endpoint', models.URLField(max_length=500, verbose_name='Ragflow API 端点')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API 密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Ragflow 配置',
                'verbose_name_plural': 'Ragflow 配置',
                'ordering': ['name'],
            },
        ),
    ]
