# Generated by Django 4.2.11 on 2026-07-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ragflow_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragflowconfig",
            name="chat_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Chat Assistant ID"
            ),
        ),
    ]
