# Generated by Django 4.2.30 on 2026-07-28 16:33
#
# RagflowConfig.api_key 由明文 CharField 切换为 EncryptedCharField：
# 1. AlterField 变更字段类型（DB 层仍为 varchar，仅放宽长度上限）；
# 2. RunPython 把已存在的明文值重新以密文落库（双向，支持回滚）。

from django.conf import settings
from django.db import migrations

import personnel.models


def encrypt_existing_api_keys(apps, schema_editor):
    """forward：把库中现存的明文 api_key 加密后重新写回。

    刻意走原生 SQL 而非 ORM ``obj.save()``：历史模型的字段已是
    EncryptedCharField，ORM 读取时会先执行 ``from_db_value`` 解密，
    对于恰好是合法 base64 的明文密钥会解出乱码再重加密，导致数据损坏。
    原生 SQL 绕过字段层，拿到的就是原始明文。
    """
    RagflowConfig = apps.get_model("ragflow_service", "RagflowConfig")
    table = RagflowConfig._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"SELECT id, api_key FROM {table} WHERE api_key IS NOT NULL AND api_key != ''"
        )
        rows = cursor.fetchall()
        for config_id, plain_key in rows:
            encrypted = personnel.models._encrypt_field(plain_key, settings.SECRET_KEY)
            cursor.execute(
                f"UPDATE {table} SET api_key = %s WHERE id = %s",
                [encrypted, config_id],
            )


def decrypt_existing_api_keys(apps, schema_editor):
    """reverse：把密文 api_key 解密回明文，便于回滚到旧版本代码。

    回滚时本函数先于 AlterField 逆操作执行（operations 逆序），
    此时字段仍是 EncryptedCharField，解密写回明文后字段再还原为 CharField。
    """
    RagflowConfig = apps.get_model("ragflow_service", "RagflowConfig")
    table = RagflowConfig._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"SELECT id, api_key FROM {table} WHERE api_key IS NOT NULL AND api_key != ''"
        )
        rows = cursor.fetchall()
        for config_id, encrypted_key in rows:
            plain = personnel.models._decrypt_field(encrypted_key, settings.SECRET_KEY)
            cursor.execute(
                f"UPDATE {table} SET api_key = %s WHERE id = %s",
                [plain, config_id],
            )


class Migration(migrations.Migration):

    dependencies = [
        ("ragflow_service", "0002_add_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ragflowconfig",
            name="api_key",
            field=personnel.models.EncryptedCharField(
                blank=True, max_length=500, null=True, verbose_name="API 密钥"
            ),
        ),
        migrations.RunPython(encrypt_existing_api_keys, decrypt_existing_api_keys),
    ]
