version: '3.8'

services:
  backend:
    image: ghcr.io/onemuggle/omni_desk_backend:latest
    env_file:
      - ./.env.production

  frontend:
    image: ghcr.io/onemuggle/omni_desk_frontend:latest

  worker:
    image: ghcr.io/onemuggle/omni_desk_backend:latest
    env_file:
      - ./.env.production