version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: omni_desk_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-omni_desk}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    ports:
      - "5433:5432" # Changed host port to avoid conflict
    command: postgres -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-omni_desk}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: omni_desk_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    image: ${DOCKER_USER:-defaultuser}/omni-desk-backend:${BACKEND_VERSION:-latest}
    build:
      context: ../..
      dockerfile: omni_desk_backend/Dockerfile
    container_name: omni_desk_backend
    command: /bin/sh -c "python manage.py migrate && python init_superuser.py && gunicorn omni_desk_backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./.env.production
    environment:
      - DJANGO_SETTINGS_MODULE=omni_desk_backend.settings
      - DJANGO_ENV=production
    restart: unless-stopped

  frontend:
    image: ${DOCKER_USER:-defaultuser}/omni-desk-frontend:${FRONTEND_VERSION:-latest}
    build:
      context: ../..
      dockerfile: omni_desk_frontend/Dockerfile
    container_name: omni_desk_frontend
    ports:
      - "80:80" # Changed host port to avoid conflict
    volumes:
      - ../../omni_desk_frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    depends_on:
      - backend
    restart: unless-stopped

  worker:
    image: ${DOCKER_USER:-defaultuser}/omni-desk-backend:${BACKEND_VERSION:-latest}
    container_name: omni_desk_worker
    command: celery -A omni_desk_backend worker -l info
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    env_file:
      - ./.env.production
    environment:
      - DJANGO_SETTINGS_MODULE=omni_desk_backend.settings
      - DJANGO_ENV=production
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume: