
services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=devdb

  redis:
    image: redis:6-alpine

  backend:
    build:
      context: ../../
      dockerfile: deployment/docker/omni_desk_backend/Dockerfile
      target: development
    volumes:
      - ../../:/usr/src/app
    working_dir: /usr/src/app/omni_desk_backend
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ../../
      dockerfile: deployment/docker/omni_desk_backend/Dockerfile
      target: development
    working_dir: /usr/src/app/omni_desk_backend
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
  frontend:
    build:
      context: ../../omni_desk_frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ../../omni_desk_frontend:/app
    ports:
      - "3000:3000"

volumes:
  postgres_data_dev: