version: '3.8'

services:
  backend:
    image: omni-desk-backend-prod:latest
    env_file:
      - ./.env.production

  frontend:
    image: omni-desk-frontend-prod:latest

  worker:
    image: omni-desk-backend-prod:latest
    env_file:
      - ./.env.production