# Generated by Django 5.1.3 on 2025-04-02 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': '试验',
                'verbose_name_plural': '试验管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('description', models.TextField(blank=True, verbose_name='时间段描述')),
            ],
            options={
                'verbose_name': '试验时间段',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experiment_type', models.CharField(choices=[('chemical', '化学实验'), ('biological', '生物实验'), ('physical', '物理实验')], max_length=20)),
                ('template_file', models.FileField(upload_to='templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='试验名称')),
                ('client', models.CharField(max_length=200, verbose_name='客户单位')),
                ('description', models.TextField(verbose_name='试验描述')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='主开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='主结束时间')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planned', max_length=20, verbose_name='试验状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('equipments', models.ManyToManyField(blank=True, related_name='trials', to='events.equipment', verbose_name='相关设备')),
                ('responsible_persons', models.ManyToManyField(related_name='trials', to='events.personnel', verbose_name='责任人')),
                ('time_slots', models.ManyToManyField(blank=True, help_text='试验具体时间段安排', related_name='trials', to='events.timeslot', verbose_name='时间段明细')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='timeslot',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_periods', to='events.trial', verbose_name='关联试验'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='prevent_time_slot_overlap'),
        ),
    ]
