# Generated by Django 5.1.3 on 2025-03-30 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trial',
            name='equipments',
            field=models.ManyToManyField(blank=True, to='events.equipment'),
        ),
        migrations.AddField(
            model_name='trial',
            name='responsible_persons',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
