# Generated by Django 5.1.3 on 2025-03-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='responsible_persons',
            field=models.ManyToManyField(to='events.personnel'),
        ),
    ]
