# Generated by Django 5.1.3 on 2025-03-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_equipment_options_remove_equipment_experiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='role',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='experiment',
        ),
        migrations.AddField(
            model_name='personnel',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
