# Generated by Django 5.1.3 on 2025-03-31 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_trial_responsible_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='end_date',
            field=models.DateTimeField(verbose_name='预期结束时间'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='start_date',
            field=models.DateTimeField(verbose_name='预期开始时间'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='实际开始时间')),
                ('end_time', models.DateTimeField(verbose_name='实际结束时间')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='events.trial')),
            ],
            options={
                'verbose_name': '试验时间段',
                'ordering': ['start_time'],
            },
        ),
    ]
