# Generated by Django 3.2 on 2025-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_documenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='experiment_info',
            field=models.TextField(blank=True, verbose_name='试验信息'),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='event',
            name='train_count',
            field=models.PositiveIntegerField(default=0, verbose_name='车次数量'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
