# Generated by Django 3.2 on 2025-03-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20250322_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('contact', models.CharField(max_length=100, verbose_name='联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='events.event')),
            ],
            options={
                'verbose_name': '负责人',
                'verbose_name_plural': '负责人管理',
            },
        ),
    ]
