# Generated by Django 5.1.3 on 2025-04-15 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_trial_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField(unique=True, verbose_name='值班日期')),
                ('duty_leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leader_schedules', to='events.personnel', verbose_name='值班领导')),
                ('duty_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_schedules', to='events.personnel', verbose_name='值班人员')),
            ],
            options={
                'verbose_name': '排班表',
                'verbose_name_plural': '排班管理',
                'constraints': [models.UniqueConstraint(fields=('duty_date',), name='unique_duty_date')],
            },
        ),
    ]
