# Generated by Django 5.1.3 on 2025-03-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_trial_delete_experiment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='trial',
            options={'ordering': ['id']},
        ),
    ]
