# Generated by Django 3.2 on 2025-03-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_responsibleperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibleperson',
            options={'ordering': ['-updated_at'], 'verbose_name': '负责人', 'verbose_name_plural': '负责人管理'},
        ),
        migrations.AddField(
            model_name='responsibleperson',
            name='event_type',
            field=models.CharField(choices=[('train', '列车调度'), ('experiment', '试验项目'), ('maintenance', '设备维护')], default='train', max_length=20, verbose_name='事件类型'),
        ),
        migrations.AddField(
            model_name='responsibleperson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='responsibleperson',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='events.event'),
        ),
    ]
