# Generated by Django 5.1.3 on 2025-04-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['duty_date'], 'verbose_name': '排班表', 'verbose_name_plural': '排班管理'},
        ),
    ]
