# Generated by Django 3.2 on 2025-03-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='user',
        ),
        migrations.AddField(
            model_name='personnel',
            name='name',
            field=models.CharField(default='', help_text='请输入人员姓名', max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='phone',
            field=models.CharField(default='', help_text='请输入联系电话', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
