# Generated by Django 3.2 on 2025-03-27 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_auto_20250327_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='user',
            field=models.ForeignKey(blank=True, help_text='关联创建用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
