# Generated by Django 5.1.3 on 2025-08-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='领导顺序名称')),
                ('sequence', models.JSONField(default=list, verbose_name='领导ID顺序列表')),
            ],
            options={
                'verbose_name': '领导顺序',
                'verbose_name_plural': '领导顺序管理',
            },
        ),
        migrations.CreateModel(
            name='PersonnelSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='人员顺序名称')),
                ('sequence', models.JSONField(default=list, verbose_name='人员ID顺序列表')),
            ],
            options={
                'verbose_name': '人员顺序',
                'verbose_name_plural': '人员顺序管理',
            },
        ),
    ]
