# Generated by Django 5.1.3 on 2025-04-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('manage_users', '可以管理用户'), ('manage_calendar', '可以管理日历'), ('manage_documents', '可以管理文档'), ('manage_equipment', '可以管理设备'), ('manage_settings', '可以管理系统设置')], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('manager', '经理'), ('user', '普通用户')], default='user', max_length=20),
        ),
    ]
