# Generated by Django 4.2.11 on 2026-06-05 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="批次ID"
                    ),
                ),
                (
                    "actor",
                    models.CharField(blank=True, max_length=100, verbose_name="操作者"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("link", "绑定"),
                            ("unlink", "解绑"),
                            ("link_skipped", "绑定跳过"),
                            ("unlink_skipped", "解绑跳过"),
                        ],
                        max_length=32,
                        verbose_name="动作",
                    ),
                ),
                (
                    "old_personnel_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="原 personnel.id"
                    ),
                ),
                (
                    "new_personnel_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="新 personnel.id"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_log_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="目标用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户-人员关联审计日志",
                "verbose_name_plural": "用户-人员关联审计日志",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["batch_id", "action"],
                        name="users_audit_batch_i_4b3733_idx",
                    )
                ],
            },
        ),
    ]
