# Generated by Django 5.1.3 on 2025-05-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('manage_users', '可以管理用户'), ('manage_calendar', '可以管理日历'), ('manage_documents', '可以管理文档'), ('manage_equipment', '可以管理设备'), ('manage_settings', '可以管理系统设置'), ('manage_schedule', '可以管理日程'), ('manage_trials', '可以管理试验'), ('manage_personnel', '可以管理人员'), ('manage_announcements', '可以管理公告'), ('use_ai_chat', '可以使用AI聊天'), ('analyze_files', '可以分析文件')], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
