# Generated by Django 4.2.30 on 2026-08-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auditlogentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="guest_until",
            field=models.DateTimeField(
                blank=True,
                help_text="仅游客账号使用;超过此时间后账号被拦截并由定时任务清理",
                null=True,
                verbose_name="游客过期时间",
            ),
        ),
    ]
