# Generated by Django 4.2.30 on 2026-08-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_guest_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlogentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("personnel_link", "用户-人员关联"),
                    ("group_change", "组变更"),
                    ("permission_change", "权限变更"),
                ],
                db_index=True,
                default="personnel_link",
                max_length=32,
                verbose_name="审计类别",
            ),
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="action",
            field=models.CharField(max_length=32, verbose_name="动作"),
        ),
    ]
