# Generated by Django 5.1.3 on 2025-08-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
