# Generated by Django 5.1.3 on 2025-08-26 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_personnel', to=settings.AUTH_USER_MODEL, verbose_name='指派人'),
        ),
    ]
