# Generated by Django 5.1.3 on 2025-08-31 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_leadersequence_personnel_personnelsequence_personnel'),
        ('users', '0007_customuser_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personnel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='events.personnel', verbose_name='关联人员'),
        ),
    ]
