# Generated by Django 5.1.3 on 2025-09-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='real_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='真实姓名'),
        ),
    ]
