# Generated by Django 4.2.11 on 2025-12-12 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_position'),
        ('users', '0011_remove_customuser_phone_number_phonenumber'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='customuser',
                    name='personnel',
                    field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='personnel.personnel', verbose_name='关联人员'),
                ),
            ],
            database_operations=[],
        ),
    ]
