# Generated by Django 4.2.11 on 2025-12-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20251211_1105'),
        ('users', '0011_remove_customuser_phone_number_phonenumber'),
    ]

def transfer_personnel_foreign_keys(apps, schema_editor):
    """
    在 CustomUser.personnel 的 to 字段从 events.Personnel 切换到 personnel.Personnel 之前，
    将旧的外键关系迁移到新的外键关系。
    """
    CustomUser = apps.get_model('users', 'CustomUser')
    OldPersonnel = apps.get_model('events', 'Personnel')
    NewPersonnel = apps.get_model('personnel', 'Personnel')

    for user in CustomUser.objects.filter(personnel__isnull=False):
        try:
            # personnel_id 此时仍然指向 old_personnel
            old_personnel_id = user.personnel_id
            old_personnel_name = OldPersonnel.objects.get(id=old_personnel_id).name
            
            # 在新模型中找到对应的记录
            new_personnel = NewPersonnel.objects.get(name=old_personnel_name, id_card_number=f"temp_id_{old_personnel_id}")
            
            # 直接更新外键ID
            user.personnel_id = new_personnel.id
            user.save(update_fields=['personnel_id'])

        except OldPersonnel.DoesNotExist:
            # 如果旧的人员记录不存在，则将关联设置为空
            user.personnel = None
            user.save(update_fields=['personnel'])
        except NewPersonnel.DoesNotExist:
            # 如果在新表中找不到对应的记录，也设置为空
            user.personnel = None
            user.save(update_fields=['personnel'])

class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20251211_1105'),
        ('users', '0011_remove_customuser_phone_number_phonenumber'),
        ('events', '0019_alter_leadersequence_personnel_and_more'),
    ]

    operations = [
        # 在 AlterField 之前运行数据迁移
        migrations.RunPython(transfer_personnel_foreign_keys),
        
        migrations.AlterField(
            model_name='customuser',
            name='personnel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='personnel.personnel', verbose_name='关联人员'),
        ),
    ]
