# Generated by Django 3.2.12 on 2025-12-12 07:57

from django.db import migrations

def migrate_roles_to_groups(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    Group = apps.get_model('auth', 'Group')

    admin_group, _ = Group.objects.get_or_create(name='Admin')
    manager_group, _ = Group.objects.get_or_create(name='Manager')
    user_group, _ = Group.objects.get_or_create(name='User')

    for user in CustomUser.objects.all():
        if hasattr(user, '_role_bak'):
            if user._role_bak == 'admin':
                user.groups.add(admin_group)
            elif user._role_bak == 'manager':
                user.groups.add(manager_group)
            else:
                user.groups.add(user_group)

def backup_role_field(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    for user in CustomUser.objects.all():
        user._role_bak = user.role
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_personnel'),
    ]

    operations = [
        migrations.RunPython(backup_role_field),
        migrations.RunPython(migrate_roles_to_groups),
    ]
