# Generated by Django 4.2.30 on 2026-07-11 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                ("file_size", models.BigIntegerField(help_text="文件大小（字节）")),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "sheet_count",
                    models.IntegerField(default=0, help_text="Excel: Sheet 数量"),
                ),
                (
                    "page_count",
                    models.IntegerField(default=0, help_text="PDF/Word: 页数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "上传文件",
                "verbose_name_plural": "上传文件",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_text",
                    models.TextField(blank=True, help_text="纯文本（用于 AI 分析）"),
                ),
                (
                    "content_markdown",
                    models.TextField(blank=True, help_text="Markdown 格式"),
                ),
                (
                    "content_json",
                    models.JSONField(blank=True, default=dict, help_text="结构化数据"),
                ),
                (
                    "sheets_data",
                    models.JSONField(
                        blank=True, default=list, help_text="Excel Sheet 数据"
                    ),
                ),
                ("row_count", models.IntegerField(default=0)),
                ("column_count", models.IntegerField(default=0)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="file_processing.uploadedfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "处理结果",
                "verbose_name_plural": "处理结果",
            },
        ),
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("summary", "数据摘要"),
                            ("statistics", "统计分析"),
                            ("quality", "数据质量"),
                            ("query", "自然语言查询"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "query_text",
                    models.TextField(blank=True, help_text="用户查询（仅 query 类型）"),
                ),
                ("result_text", models.TextField(help_text="AI 生成的结果")),
                (
                    "result_data",
                    models.JSONField(blank=True, default=dict, help_text="结构化结果"),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True, help_text="Ollama 模型名", max_length=100
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                ("processing_time_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="file_processing.uploadedfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 分析",
                "verbose_name_plural": "AI 分析",
                "ordering": ["-created_at"],
            },
        ),
    ]
