version: '3.8'

services:
  frontend:
    image: ${DOCKER_USER:-defaultuser}/omni-desk-frontend:${FRONTEND_VERSION:-latest}
    build:
      context: ../../omni_desk_frontend
      dockerfile: Dockerfile
    container_name: omni_desk_frontend
    expose:
      - 80 # Frontend will be exposed via Nginx
    networks:
      - omni_desk_network
    restart: unless-stopped

networks:
  omni_desk_network:
    name: omni_desk_network
    external: true