# Generated by Django 4.2.11 on 2026-01-17 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告管理',
                'ordering': ['-created_at'],
                'permissions': [('manage_announcements', 'Can manage announcements')],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experiment_type', models.CharField(choices=[('chemical', '化学实验'), ('biological', '生物实验'), ('physical', '物理实验')], max_length=20)),
                ('template_file', models.FileField(upload_to='templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': '试验',
                'verbose_name_plural': '试验管理',
                'ordering': ['id'],
                'permissions': [('manage_equipment', 'Can manage equipment')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcement_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='试验名称')),
                ('version', models.IntegerField(default=0, verbose_name='版本号')),
                ('client', models.CharField(max_length=200, verbose_name='客户单位')),
                ('description', models.TextField(verbose_name='试验描述')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='主开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='主结束时间')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planned', max_length=20, verbose_name='试验状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('equipments', models.ManyToManyField(blank=True, related_name='trials', to='events.equipment', verbose_name='相关设备')),
                ('responsible_persons', models.ManyToManyField(related_name='trials', to='personnel.personnel', verbose_name='责任人')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('description', models.TextField(blank=True, verbose_name='时间段描述')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='events.trial', verbose_name='关联试验')),
            ],
            options={
                'verbose_name': '试验时间段',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField(unique=True, verbose_name='值班日期')),
                ('duty_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_schedules', to='personnel.personnel', verbose_name='值班领导')),
                ('duty_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_schedules', to='personnel.personnel', verbose_name='值班人员')),
            ],
            options={
                'verbose_name': '排班表',
                'verbose_name_plural': '排班管理',
                'ordering': ['duty_date'],
                'permissions': [('manage_schedule', 'Can manage schedule'), ('manage_announcements', 'Can manage announcements')],
            },
        ),
        migrations.CreateModel(
            name='PersonnelSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='人员顺序名称')),
                ('sequence', models.JSONField(default=list, verbose_name='工作日人员ID顺序列表')),
                ('holiday_sequence', models.JSONField(blank=True, default=list, verbose_name='节假日人员ID顺序列表')),
                ('holiday_personnel', models.ManyToManyField(blank=True, related_name='holiday_personnel_sequences', to='personnel.personnel', verbose_name='节假日人员')),
                ('personnel', models.ManyToManyField(related_name='personnel_sequences', to='personnel.personnel', verbose_name='工作日人员')),
            ],
            options={
                'verbose_name': '人员顺序',
                'verbose_name_plural': '人员顺序管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LeaderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='领导顺序名称')),
                ('sequence', models.JSONField(default=list, verbose_name='领导ID顺序列表')),
                ('personnel', models.ManyToManyField(related_name='leader_sequences', to='personnel.personnel')),
            ],
            options={
                'verbose_name': '领导顺序',
                'verbose_name_plural': '领导顺序管理',
                'ordering': ['id'],
            },
        ),
    ]
