# Generated by Django 5.1.3 on 2025-04-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='time_slots',
        ),
    ]
