# Generated by Django 5.1.3 on 2025-04-03 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_trial_time_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='events.trial', verbose_name='关联试验'),
        ),
    ]
