# Generated by Django 4.2.30 on 2026-05-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='主结束时间'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='主开始时间'),
        ),
    ]
