# Generated by Django 5.1.3 on 2025-04-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_timeslot_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='version',
            field=models.IntegerField(default=0, verbose_name='版本号'),
        ),
    ]
