# Generated by Django 4.2.11 on 2026-06-06 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("personnel", "0005_alter_familymember_id_card_number_and_more"),
        ("events", "0003_alter_trial_end_date_alter_trial_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleSwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("duty_person", "值班人员"),
                            ("duty_leader", "值班领导"),
                        ],
                        default="duty_person",
                        max_length=20,
                        verbose_name="换岗范围",
                    ),
                ),
                ("reason", models.CharField(max_length=500, verbose_name="申请理由")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待接收方确认"),
                            ("approved", "已生效(双方互认)"),
                            ("rejected_by_target", "接收方已拒绝"),
                            ("cancelled", "申请方已撤销"),
                            ("expired", "已超时失效"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="状态",
                    ),
                ),
                (
                    "target_decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="接收方决策时间"
                    ),
                ),
                (
                    "target_decision_note",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="接收方备注"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生效时间"
                    ),
                ),
                (
                    "approval_note",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="生效备注"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, verbose_name="失效时间(默认 48h)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_swap_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人(本设计中=接收方 user_account)",
                    ),
                ),
                (
                    "original_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_swap_requests",
                        to="events.schedule",
                        verbose_name="原排班",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_swap_requests",
                        to="personnel.personnel",
                        verbose_name="申请发起人",
                    ),
                ),
                (
                    "target_personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_swap_requests",
                        to="personnel.personnel",
                        verbose_name="接收换班者",
                    ),
                ),
                (
                    "target_schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="若为空=单方面替班;若有值=双向对调(决策 2C)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_swap_requests",
                        to="events.schedule",
                        verbose_name="对调排班(可选)",
                    ),
                ),
            ],
            options={
                "verbose_name": "排班换班申请",
                "verbose_name_plural": "排班换班申请",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleSwapAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(max_length=30, verbose_name="原状态")),
                ("to_status", models.CharField(max_length=30, verbose_name="新状态")),
                (
                    "note",
                    models.CharField(blank=True, max_length=500, verbose_name="备注"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="swap_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
                (
                    "swap_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="events.scheduleswaprequest",
                        verbose_name="关联换班申请",
                    ),
                ),
            ],
            options={
                "verbose_name": "换班审计日志",
                "verbose_name_plural": "换班审计日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="scheduleswaprequest",
            index=models.Index(
                fields=["status", "expires_at"], name="swap_status_expires_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleswaprequest",
            index=models.Index(
                fields=["requester", "status"], name="swap_requester_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleswaprequest",
            index=models.Index(
                fields=["target_personnel", "status"], name="swap_target_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleswaprequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("original_schedule",),
                name="uniq_active_swap_per_schedule",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleswapauditlog",
            index=models.Index(
                fields=["swap_request", "-created_at"],
                name="events_sche_swap_re_e3db98_idx",
            ),
        ),
    ]
