# Generated by Django 4.2.30 on 2026-07-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_scheduleswaprequest_scheduleswapauditlog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
    ]
