# Generated by Django 5.1.3 on 2025-08-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['id'], 'permissions': [('manage_equipment', 'Can manage equipment')], 'verbose_name': '试验', 'verbose_name_plural': '试验管理'},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['id'], 'permissions': [('manage_personnel', 'Can manage personnel')]},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['duty_date'], 'permissions': [('manage_schedule', 'Can manage schedule'), ('manage_announcements', 'Can manage announcements')], 'verbose_name': '排班表', 'verbose_name_plural': '排班管理'},
        ),
    ]
