# Generated by Django 5.1.3 on 2025-08-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_leadersequence_personnelsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadersequence',
            name='personnel',
            field=models.ManyToManyField(related_name='leader_sequences', to='events.personnel'),
        ),
        migrations.AddField(
            model_name='personnelsequence',
            name='personnel',
            field=models.ManyToManyField(related_name='personnel_sequences', to='events.personnel'),
        ),
    ]
