# Generated by Django 5.1.3 on 2025-09-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_leadersequence_personnel_personnelsequence_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='职位名称')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位管理',
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='events.position', verbose_name='职位'),
        ),
    ]
