# Generated by Django 5.1.3 on 2025-09-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_position_personnel_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='department',
        ),
    ]
