# Generated by Django 5.1.3 on 2025-09-04 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_personnel_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='phone',
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='电话号码')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='events.personnel', verbose_name='人员')),
            ],
            options={
                'verbose_name': '电话号码',
                'verbose_name_plural': '电话号码',
            },
        ),
    ]
