# Generated by Django 5.1.3 on 2025-11-24 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_personnel_phone_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duty_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_schedules', to='events.personnel', verbose_name='值班领导'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='duty_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_schedules', to='events.personnel', verbose_name='值班人员'),
        ),
    ]
