# Generated by Django 5.1.3 on 2025-11-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_holiday_date_holiday_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelsequence',
            name='holiday_personnel',
            field=models.ManyToManyField(blank=True, related_name='holiday_personnel_sequences', to='events.personnel', verbose_name='节假日人员'),
        ),
        migrations.AddField(
            model_name='personnelsequence',
            name='holiday_sequence',
            field=models.JSONField(blank=True, default=list, verbose_name='节假日人员ID顺序列表'),
        ),
        migrations.AlterField(
            model_name='personnelsequence',
            name='personnel',
            field=models.ManyToManyField(related_name='personnel_sequences', to='events.personnel', verbose_name='工作日人员'),
        ),
        migrations.AlterField(
            model_name='personnelsequence',
            name='sequence',
            field=models.JSONField(default=list, verbose_name='工作日人员ID顺序列表'),
        ),
    ]
