# Generated by Django 4.2.11 on 2025-12-11 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_position'),
        ('events', '0018_personnelsequence_holiday_personnel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadersequence',
            name='personnel',
            field=models.ManyToManyField(related_name='leader_sequences', to='personnel.personnel'),
        ),
        migrations.AlterField(
            model_name='personnelsequence',
            name='holiday_personnel',
            field=models.ManyToManyField(blank=True, related_name='holiday_personnel_sequences', to='personnel.personnel', verbose_name='节假日人员'),
        ),
        migrations.AlterField(
            model_name='personnelsequence',
            name='personnel',
            field=models.ManyToManyField(related_name='personnel_sequences', to='personnel.personnel', verbose_name='工作日人员'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='personnel.personnel', verbose_name='人员'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='duty_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_schedules', to='personnel.personnel', verbose_name='值班领导'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='duty_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_schedules', to='personnel.personnel', verbose_name='值班人员'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='responsible_persons',
            field=models.ManyToManyField(related_name='trials', to='personnel.personnel', verbose_name='责任人'),
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
