# Generated by Django 4.2.11 on 2025-12-11 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_leadersequence_personnel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
