# Generated by Django 4.2.11 on 2026-01-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_phonenumber_personnel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadersequence',
            options={'ordering': ['id'], 'verbose_name': '领导顺序', 'verbose_name_plural': '领导顺序管理'},
        ),
        migrations.AlterModelOptions(
            name='personnelsequence',
            options={'ordering': ['id'], 'verbose_name': '人员顺序', 'verbose_name_plural': '人员顺序管理'},
        ),
    ]
