# Generated by Django 4.2.11 on 2025-12-11 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('id_card_number', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('address', models.TextField(blank=True, verbose_name='家庭住址')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('status', models.CharField(choices=[('active', '在职'), ('inactive', '离职')], default='active', max_length=10, verbose_name='员工状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '人员信息',
                'verbose_name_plural': '人员信息',
                'ordering': ['-hire_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='公司名称')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('description', models.TextField(blank=True, verbose_name='工作描述')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='personnel.personnel', verbose_name='关联人员')),
            ],
            options={
                'verbose_name': '工作经历',
                'verbose_name_plural': '工作经历',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200, verbose_name='毕业院校')),
                ('degree', models.CharField(max_length=100, verbose_name='学历')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='personnel.personnel', verbose_name='关联人员')),
            ],
            options={
                'verbose_name': '教育背景',
                'verbose_name_plural': '教育背景',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, verbose_name='合同编号')),
                ('start_date', models.DateField(verbose_name='合同开始日期')),
                ('end_date', models.DateField(verbose_name='合同结束日期')),
                ('contract_type', models.CharField(choices=[('permanent', '长期合同'), ('fixed-term', '固定期限合同')], max_length=20, verbose_name='合同类型')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='personnel.personnel', verbose_name='关联人员')),
            ],
            options={
                'verbose_name': '合同信息',
                'verbose_name_plural': '合同信息',
            },
        ),
    ]
