# Generated by Django 5.1.3 on 2025-12-11 03:05

from django.db import migrations

def migrate_personnel_data(apps, schema_editor):
    """
    将数据从旧的 events.Personnel 模型迁移到新的 personnel.Personnel 模型。
    """
    try:
        # 获取历史模型
        OldPersonnel = apps.get_model('events', 'Personnel')
        OldPhoneNumber = apps.get_model('events', 'PhoneNumber')
        NewPersonnel = apps.get_model('personnel', 'Personnel')
    except LookupError:
        # 如果旧模型不存在（例如，在全新的安装中），则直接跳过迁移
        return

    new_personnel_list = []
    for old_person in OldPersonnel.objects.all():
        # 尝试获取关联的电话号码
        phone_number_instance = OldPhoneNumber.objects.filter(personnel_id=old_person.id).first()
        phone_number = phone_number_instance.number if phone_number_instance else ""

        # 尝试获取职位名称
        position_name = old_person.position.name if old_person.position else ""

        new_personnel_list.append(
            NewPersonnel(
                name=old_person.name,
                position=position_name,
                phone_number=phone_number,
                # 其他字段可以根据需要设置默认值或留空
                # 例如: id_card_number, date_of_birth 等在新模型中是必须的，
                # 但在旧模型中不存在，这里我们暂时留空，后续可能需要手动填充。
                # 为了满足 unique 约束，我们使用旧的 ID 生成一个临时的唯一值。
                id_card_number=f"temp_id_{old_person.id}",
            )
        )
    
    # 批量创建以提高性能
    if new_personnel_list:
        NewPersonnel.objects.bulk_create(new_personnel_list, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
        # 确保此迁移在 events 应用的相应模型创建之后运行
        ('events', '0001_initial'), 
    ]

    operations = [
        # migrations.RunPython(migrate_personnel_data),
    ]
