# Generated by Django 4.2.11 on 2026-01-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号'),
        ),
    ]
