# Generated by Django 4.2.11 on 2026-02-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_personnel_id_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证号'),
        ),
    ]
