# Generated by Django 4.2.11 on 2025-12-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20251211_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='职位名称')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位管理',
            },
        ),
    ]
