# Generated by Django 4.2.11 on 2025-12-14 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=200, verbose_name='资质名称')),
                ('issue_date', models.DateField(verbose_name='生效日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('certificate_id', models.CharField(blank=True, max_length=100, verbose_name='证件编号')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='personnel.personnel', verbose_name='关联人员')),
            ],
            options={
                'verbose_name': '职业资质',
                'verbose_name_plural': '职业资质',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('relationship', models.CharField(max_length=50, verbose_name='与本人关系')),
                ('id_card_number', models.CharField(blank=True, max_length=18, verbose_name='身份证号')),
                ('contact_number', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='personnel.personnel', verbose_name='关联人员')),
            ],
            options={
                'verbose_name': '家庭成员',
                'verbose_name_plural': '家庭成员',
            },
        ),
    ]
