# Generated by Django 4.2.30 on 2026-05-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_personnel_id_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='姓名'),
        ),
    ]
