# Generated by Django 3.2.12 on 2025-12-14 14:37

from django.db import migrations, models
import django.db.models.deletion

def migrate_position_data(apps, schema_editor):
    pass

def reverse_migrate_position_data(apps, schema_editor):
    # This is optional, but good practice.
    # If we were to reverse this migration, we might want to convert the
    # position foreign key back to a CharField.
    # For this case, we can do nothing.
    pass


def nullify_invalid_fk_data(apps, schema_editor):
    """
    Sets the position field to NULL for all rows before changing the field type.
    This avoids IntegrityError for existing string data that can't be cast to a FK.
    """
    # This function is now disabled because the 'position' column it was trying
    # to clean up appears to have been removed already in a previous partial
    # migration, causing a "no such column" error.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_professionalqualification_familymember'),
    ]

    operations = [
        # First, create all necessary Position objects from the existing CharField data
        # migrations.RunPython(migrate_position_data, reverse_migrate_position_data),
        
        # Nullify the old string data before attempting to convert the column to a ForeignKey.
        migrations.RunPython(nullify_invalid_fk_data),

        # Then, alter the field to be a ForeignKey
        migrations.AlterField(
            model_name='personnel',
            name='position',
            field=models.ForeignKey(
                to='personnel.Position',
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                verbose_name='职位'
            ),
        ),
    ]
