# Generated by Django 4.2.30 on 2026-05-19 14:26

from django.db import migrations
import personnel.models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_alter_personnel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='id_card_number',
            field=personnel.models.EncryptedCharField(blank=True, max_length=18, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='id_card_number',
            field=personnel.models.EncryptedCharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证号'),
        ),
    ]
