# Generated by Django 3.2.12 on 2025-12-14 14:37

from django.db import migrations, models
import django.db.models.deletion

def migrate_position_data(apps, schema_editor):
    Personnel = apps.get_model('personnel', 'Personnel')
    Position = apps.get_model('personnel', 'Position')
    for person in Personnel.objects.all():
        # The `position` field is still a CharField at this point in the migration.
        position_name = person.position
        if position_name:
            position_obj, created = Position.objects.get_or_create(name=position_name)
            # We're about to change the field to a ForeignKey, so we need to
            # put the foreign key ID into the column *before* the AlterField.
            person.position = position_obj.pk
            person.save()

def reverse_migrate_position_data(apps, schema_editor):
    # This is optional, but good practice.
    # If we were to reverse this migration, we might want to convert the
    # position foreign key back to a CharField.
    # For this case, we can do nothing.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_professionalqualification_familymember'),
    ]

    operations = [
        # First, create all necessary Position objects from the existing CharField data
        migrations.RunPython(migrate_position_data, reverse_migrate_position_data),
        
        # Then, alter the field to be a ForeignKey
        migrations.AlterField(
            model_name='personnel',
            name='position',
            field=models.ForeignKey(
                to='personnel.Position',
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                verbose_name='职位'
            ),
        ),
    ]
