# Generated by Django 4.2.30 on 2026-06-24 05:00

from django.db import migrations
import personnel.models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_alter_familymember_id_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='id_card_number',
            field=personnel.models.EncryptedCharField(blank=True, max_length=64, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='id_card_number',
            field=personnel.models.EncryptedCharField(blank=True, max_length=64, null=True, unique=True, verbose_name='身份证号'),
        ),
    ]
