# Generated by Django 4.2.11 on 2026-01-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_auto_20251214_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['id'], 'verbose_name': '家庭成员', 'verbose_name_plural': '家庭成员'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': '职位', 'verbose_name_plural': '职位管理'},
        ),
        migrations.AlterModelOptions(
            name='professionalqualification',
            options={'ordering': ['id'], 'verbose_name': '职业资质', 'verbose_name_plural': '职业资质'},
        ),
    ]
