# Generated by Django 4.2.30 on 2026-07-29 15:20
#
# P0-B: id_card_number 由 XOR+base64 假加密迁移到 Fernet 认证加密。
# AlterField 仅变更字段类型/max_length,不触碰存量数据;
# RunPython 负责把旧 XOR 密文解密为明文后重新 Fernet 加密。

import base64
import hashlib

from cryptography.fernet import Fernet, InvalidToken
from django.conf import settings
from django.db import connection, migrations
import personnel.fields

_TABLES = ("personnel_personnel", "personnel_familymember")


def _legacy_xor_decrypt(encoded_value: str, key: str) -> str:
    """旧版 _decrypt_field 的等价实现(内联,避免数据迁移依赖应用代码)。"""
    key_bytes = hashlib.sha256(key.encode()).digest()
    encrypted = base64.b64decode(encoded_value.encode("utf-8"))
    decrypted = bytes(e ^ key_bytes[i % len(key_bytes)] for i, e in enumerate(encrypted))
    return decrypted.decode("utf-8")


def _legacy_xor_encrypt(value: str, key: str) -> str:
    """旧版 _encrypt_field 的等价实现(回滚用)。"""
    key_bytes = hashlib.sha256(key.encode()).digest()
    value_bytes = value.encode("utf-8")
    encrypted = bytes(v ^ key_bytes[i % len(key_bytes)] for i, v in enumerate(value_bytes))
    return base64.b64encode(encrypted).decode("utf-8")


def _fernet() -> Fernet:
    key = base64.urlsafe_b64encode(hashlib.sha256(settings.SECRET_KEY.encode()).digest())
    return Fernet(key)


def xor_to_fernet(apps, schema_editor):
    """存量数据:旧 XOR 密文 → 明文 → Fernet 密文。

    直接走原生 SQL 读写,绕开 ORM 字段转换(历史模型已指向新字段类,
    经 ORM 读取会尝试 Fernet 解密旧数据而失败)。
    已是 Fernet 格式或无法解析的行原样保留,保证幂等。
    """
    fernet = _fernet()
    with connection.cursor() as cursor:
        for table in _TABLES:
            cursor.execute(
                f"SELECT id, id_card_number FROM {table} "
                "WHERE id_card_number IS NOT NULL AND id_card_number != ''"
            )
            rows = cursor.fetchall()
            for pk, raw in rows:
                try:
                    plaintext = _legacy_xor_decrypt(raw, settings.SECRET_KEY)
                except Exception:
                    continue  # 非旧格式(可能已迁移或损坏),跳过
                token = fernet.encrypt(plaintext.encode()).decode()
                cursor.execute(
                    f"UPDATE {table} SET id_card_number = %s WHERE id = %s", [token, pk]
                )


def fernet_to_xor(apps, schema_editor):
    """回滚:Fernet 密文 → 明文 → 旧 XOR 密文。"""
    fernet = _fernet()
    with connection.cursor() as cursor:
        for table in _TABLES:
            cursor.execute(
                f"SELECT id, id_card_number FROM {table} "
                "WHERE id_card_number IS NOT NULL AND id_card_number != ''"
            )
            rows = cursor.fetchall()
            for pk, raw in rows:
                try:
                    plaintext = fernet.decrypt(raw.encode()).decode()
                except InvalidToken:
                    continue  # 非 Fernet 格式,跳过
                legacy = _legacy_xor_encrypt(plaintext, settings.SECRET_KEY)
                cursor.execute(
                    f"UPDATE {table} SET id_card_number = %s WHERE id = %s", [legacy, pk]
                )


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0006_alter_familymember_id_card_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymember",
            name="id_card_number",
            field=personnel.fields.EncryptedCharField(
                blank=True, max_length=256, verbose_name="身份证号"
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="id_card_number",
            field=personnel.fields.EncryptedCharField(
                blank=True,
                max_length=256,
                null=True,
                unique=True,
                verbose_name="身份证号",
            ),
        ),
        migrations.RunPython(xor_to_fernet, fernet_to_xor),
    ]
