# Generated by Django 5.1.3 on 2025-08-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_tag_book_author_book_cover_image_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='heading_structure',
            field=models.JSONField(blank=True, default=list, verbose_name='章节标题结构'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='image_metadata',
            field=models.JSONField(blank=True, default=list, verbose_name='图片元数据'),
        ),
    ]
