# Generated by Django 5.1.3 on 2025-08-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_book_project_documenttemplate_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='extracted_text',
            field=models.TextField(blank=True, verbose_name='提取文本'),
        ),
    ]
