# /etc/nginx/sites-available/omni_desk

server {
    listen 80;
    server_name your_domain.com www.your_domain.com; # Replace with your domain

    # Location for Gunicorn socket
    location / {
        proxy_pass http://unix:/var/run/gunicorn.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Location for static files
    location /static/ {
        alias /var/www/omni_desk/omni_desk_backend/staticfiles/;
    }

    # Location for media files
    location /media/ {
        alias /var/www/omni_desk/omni_desk_backend/mediafiles/;
    }

    # Location for frontend build
    location /app/ {
        alias /var/www/omni_desk/frontend_build/;
        try_files $uri $uri/ /index.html;
    }
}