# Generated by Django 5.1.3 on 2025-09-04 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='序列号')),
                ('model_name', models.CharField(max_length=100, verbose_name='型号名称')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('calibration_accuracy', models.FloatField(verbose_name='校准精度')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('last_calibration_date', models.DateField(blank=True, null=True, verbose_name='上次校准日期')),
                ('calibration_interval_days', models.IntegerField(default=365, verbose_name='校准周期（天）')),
                ('status', models.CharField(choices=[('in_stock', '库存中'), ('in_use', '使用中'), ('under_calibration', '校准中'), ('retired', '已报废')], default='in_stock', max_length=20, verbose_name='状态')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='存放位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '传感器',
                'verbose_name_plural': '传感器管理',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_date', models.DateField(verbose_name='提醒日期')),
                ('is_sent', models.BooleanField(default=False, verbose_name='是否已发送')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='发送日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_reminder', to='sensor_management.sensor', verbose_name='传感器')),
            ],
            options={
                'verbose_name': '校准提醒',
                'verbose_name_plural': '校准提醒',
                'ordering': ['remind_date'],
            },
        ),
        migrations.CreateModel(
            name='SensorMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', '入库'), ('out', '出库')], max_length=10, verbose_name='出入库类型')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='出入库日期')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('destination_source', models.CharField(blank=True, max_length=200, verbose_name='去向/来源')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人员')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='sensor_management.sensor', verbose_name='传感器')),
            ],
            options={
                'verbose_name': '传感器出入库记录',
                'verbose_name_plural': '传感器出入库记录',
                'ordering': ['-movement_date'],
            },
        ),
    ]
