# Generated by Django 4.2.11 on 2026-01-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure_value', models.FloatField(verbose_name='压力值')),
                ('positive_trip_voltage_1', models.FloatField(verbose_name='正行程电压1')),
                ('positive_trip_voltage_2', models.FloatField(verbose_name='正行程电压2')),
                ('positive_trip_voltage_3', models.FloatField(verbose_name='正行程电压3')),
                ('negative_trip_voltage_1', models.FloatField(verbose_name='负行程电压1')),
                ('negative_trip_voltage_2', models.FloatField(verbose_name='负行程电压2')),
                ('negative_trip_voltage_3', models.FloatField(verbose_name='负行程电压3')),
            ],
            options={
                'verbose_name': '校准数据点',
                'verbose_name_plural': '校准数据点',
                'ordering': ['pressure_value'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_date', models.DateField(verbose_name='提醒日期')),
                ('is_sent', models.BooleanField(default=False, verbose_name='是否已发送')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='发送日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '校准提醒',
                'verbose_name_plural': '校准提醒',
                'ordering': ['remind_date'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='传感器名称')),
                ('room_temperature', models.FloatField(blank=True, null=True, verbose_name='室温')),
                ('relative_humidity', models.FloatField(blank=True, null=True, verbose_name='相对湿度')),
                ('sensor_number', models.CharField(max_length=100, unique=True, verbose_name='传感器编号')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='序列号')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='制造商')),
                ('calibration_accuracy', models.CharField(blank=True, max_length=50, null=True, verbose_name='校准精度')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('last_calibration_date', models.DateField(blank=True, null=True, verbose_name='上次校准日期')),
                ('calibration_interval_days', models.IntegerField(default=365, verbose_name='校准周期（天）')),
                ('current_quantity', models.IntegerField(default=0, verbose_name='当前数量')),
                ('status', models.CharField(choices=[('in_stock', '库存中'), ('in_use', '使用中'), ('under_calibration', '校准中'), ('retired', '已报废')], default='in_stock', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '传感器',
                'verbose_name_plural': '传感器管理',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='SensorCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_instrument', models.CharField(max_length=255, verbose_name='校准仪器')),
                ('calibration_range', models.CharField(max_length=100, verbose_name='校准范围')),
                ('calibration_date', models.DateField(verbose_name='校准日期')),
                ('non_linearity', models.FloatField(blank=True, null=True, verbose_name='非线性度')),
                ('hysteresis', models.FloatField(blank=True, null=True, verbose_name='迟滞')),
                ('resonant_frequency', models.FloatField(blank=True, null=True, verbose_name='共振频率')),
                ('repeatability', models.FloatField(blank=True, null=True, verbose_name='重复性')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='精度')),
                ('rise_time', models.FloatField(blank=True, null=True, verbose_name='上升时间')),
                ('sensitivity', models.FloatField(blank=True, null=True, verbose_name='灵敏度')),
                ('calibration_equation', models.CharField(blank=True, default='', max_length=255, verbose_name='校准方程')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '传感器校准记录',
                'verbose_name_plural': '传感器校准记录',
                'ordering': ['-calibration_date'],
            },
        ),
        migrations.CreateModel(
            name='SensorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '传感器类别',
                'verbose_name_plural': '传感器类别管理',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', '入库'), ('out', '出库')], max_length=10, verbose_name='出入库类型')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='出入库日期')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('destination_source', models.CharField(blank=True, max_length=200, verbose_name='去向/来源')),
            ],
            options={
                'verbose_name': '传感器出入库记录',
                'verbose_name_plural': '传感器出入库记录',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='位置名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '存放位置',
                'verbose_name_plural': '存放位置管理',
                'ordering': ['name'],
            },
        ),
    ]
