# Generated by Django 4.2.11 on 2026-01-17 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sensormovement',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人员'),
        ),
        migrations.AddField(
            model_name='sensormovement',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='sensor_management.sensor', verbose_name='传感器'),
        ),
        migrations.AddField(
            model_name='sensorcalibration',
            name='calibrated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations_done', to=settings.AUTH_USER_MODEL, verbose_name='校准人'),
        ),
        migrations.AddField(
            model_name='sensorcalibration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='sensorcalibration',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='sensor_management.sensor', verbose_name='传感器'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensor_management.storagelocation', verbose_name='存放位置'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensor_management.sensorcategory', verbose_name='传感器类别'),
        ),
        migrations.AddField(
            model_name='calibrationreminder',
            name='reminded_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='被提醒用户'),
        ),
        migrations.AddField(
            model_name='calibrationreminder',
            name='sensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_reminder', to='sensor_management.sensor', verbose_name='传感器'),
        ),
        migrations.AddField(
            model_name='calibrationdatapoint',
            name='sensor_calibration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='sensor_management.sensorcalibration', verbose_name='传感器校准记录'),
        ),
    ]
