# Generated by Django 5.1.3 on 2025-10-25 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '传感器类别',
                'verbose_name_plural': '传感器类别管理',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='位置名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '存放位置',
                'verbose_name_plural': '存放位置管理',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='model_name',
        ),
        migrations.AddField(
            model_name='calibrationreminder',
            name='reminded_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='被提醒用户'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='current_quantity',
            field=models.IntegerField(default=0, verbose_name='当前数量'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_name',
            field=models.CharField(default='未知传感器', max_length=255, verbose_name='传感器名称'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_number',
            field=models.CharField(default='未知编号', max_length=100, verbose_name='传感器编号'),
        ),
        migrations.CreateModel(
            name='SensorCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_instrument', models.CharField(max_length=255, verbose_name='校准仪器')),
                ('calibration_range', models.CharField(max_length=100, verbose_name='校准范围')),
                ('calibration_date', models.DateField(verbose_name='校准日期')),
                ('room_temperature', models.FloatField(blank=True, null=True, verbose_name='室温')),
                ('relative_humidity', models.FloatField(blank=True, null=True, verbose_name='相对湿度')),
                ('pressure_values', models.JSONField(blank=True, null=True, verbose_name='压力值')),
                ('voltage_values', models.JSONField(blank=True, null=True, verbose_name='电压值')),
                ('non_linearity', models.FloatField(blank=True, null=True, verbose_name='非线性度')),
                ('hysteresis', models.FloatField(blank=True, null=True, verbose_name='迟滞')),
                ('resonant_frequency', models.FloatField(blank=True, null=True, verbose_name='谐振频率')),
                ('repeatability', models.FloatField(blank=True, null=True, verbose_name='重复性')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='准确度')),
                ('rise_time', models.FloatField(blank=True, null=True, verbose_name='上升时间')),
                ('sensitivity', models.FloatField(blank=True, null=True, verbose_name='灵敏度')),
                ('calibration_equation', models.CharField(blank=True, max_length=255, null=True, verbose_name='校准方程')),
                ('calibrator', models.CharField(blank=True, max_length=100, null=True, verbose_name='校准人')),
                ('reviewer', models.CharField(blank=True, max_length=100, null=True, verbose_name='审核人')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='sensor_management.sensor', verbose_name='传感器')),
            ],
            options={
                'verbose_name': '传感器校准记录',
                'verbose_name_plural': '传感器校准记录',
                'ordering': ['-calibration_date'],
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensor_management.sensorcategory', verbose_name='传感器类别'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensor_management.storagelocation', verbose_name='存放位置'),
        ),
    ]
