# Generated by Django 5.1.3 on 2025-10-25 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_management', '0002_sensorcategory_storagelocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_name',
        ),
        migrations.RemoveField(
            model_name='sensorcalibration',
            name='calibrator',
        ),
        migrations.RemoveField(
            model_name='sensorcalibration',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='sensorcalibration',
            name='pressure_values',
        ),
        migrations.RemoveField(
            model_name='sensorcalibration',
            name='relative_humidity',
        ),
        migrations.RemoveField(
            model_name='sensorcalibration',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='sensorcalibration',
            name='room_temperature',
        ),
        migrations.RemoveField(
            model_name='sensorcalibration',
            name='voltage_values',
        ),
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='传感器名称'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='relative_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='room_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorcalibration',
            name='calibrated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations_done', to=settings.AUTH_USER_MODEL, verbose_name='校准人'),
        ),
        migrations.AddField(
            model_name='sensorcalibration',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='sensorcalibration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='传感器编号'),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='calibration_equation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='校准方程'),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='hysteresis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='non_linearity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='repeatability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='resonant_frequency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='rise_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='sensitivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CalibrationDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure_value', models.FloatField()),
                ('positive_trip_voltage_1', models.FloatField()),
                ('positive_trip_voltage_2', models.FloatField()),
                ('positive_trip_voltage_3', models.FloatField()),
                ('negative_trip_voltage_1', models.FloatField()),
                ('negative_trip_voltage_2', models.FloatField()),
                ('negative_trip_voltage_3', models.FloatField()),
                ('sensor_calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='sensor_management.sensorcalibration')),
            ],
            options={
                'verbose_name': '校准数据点',
                'verbose_name_plural': '校准数据点',
                'ordering': ['pressure_value'],
            },
        ),
    ]
