# Generated by Django 4.2.30 on 2026-07-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_stock", "库存中"),
                    ("in_use", "使用中"),
                    ("under_calibration", "校准中"),
                    ("retired", "已报废"),
                ],
                db_index=True,
                default="in_stock",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
