# Generated by Django 5.1.3 on 2025-10-26 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_management', '0003_remove_sensor_sensor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationdatapoint',
            name='negative_trip_voltage_1',
            field=models.FloatField(verbose_name='负行程电压1'),
        ),
        migrations.AlterField(
            model_name='calibrationdatapoint',
            name='negative_trip_voltage_2',
            field=models.FloatField(verbose_name='负行程电压2'),
        ),
        migrations.AlterField(
            model_name='calibrationdatapoint',
            name='negative_trip_voltage_3',
            field=models.FloatField(verbose_name='负行程电压3'),
        ),
        migrations.AlterField(
            model_name='calibrationdatapoint',
            name='positive_trip_voltage_1',
            field=models.FloatField(verbose_name='正行程电压1'),
        ),
        migrations.AlterField(
            model_name='calibrationdatapoint',
            name='positive_trip_voltage_2',
            field=models.FloatField(verbose_name='正行程电压2'),
        ),
        migrations.AlterField(
            model_name='calibrationdatapoint',
            name='positive_trip_voltage_3',
            field=models.FloatField(verbose_name='正行程电压3'),
        ),
        migrations.AlterField(
            model_name='calibrationdatapoint',
            name='pressure_value',
            field=models.FloatField(verbose_name='压力值'),
        ),
        migrations.AlterField(
            model_name='calibrationdatapoint',
            name='sensor_calibration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='sensor_management.sensorcalibration', verbose_name='传感器校准记录'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='calibration_accuracy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='校准精度'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='relative_humidity',
            field=models.FloatField(blank=True, null=True, verbose_name='相对湿度'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='room_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='室温'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='精度'),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='hysteresis',
            field=models.FloatField(blank=True, null=True, verbose_name='迟滞'),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='non_linearity',
            field=models.FloatField(blank=True, null=True, verbose_name='非线性度'),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='repeatability',
            field=models.FloatField(blank=True, null=True, verbose_name='重复性'),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='resonant_frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='共振频率'),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='rise_time',
            field=models.FloatField(blank=True, null=True, verbose_name='上升时间'),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='sensitivity',
            field=models.FloatField(blank=True, null=True, verbose_name='灵敏度'),
        ),
    ]
