# Generated by Django 4.2.30 on 2026-07-28 12:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0006_alter_familymember_id_card_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年')),
                ('month', models.PositiveSmallIntegerField(verbose_name='月')),
                ('cycle_start_date', models.DateField(verbose_name='报告提交窗口开始')),
                ('cycle_end_date', models.DateField(verbose_name='报告审核截止')),
                ('scoring_deadline', models.DateField(verbose_name='专家打分截止')),
                ('status', models.CharField(choices=[('collecting', '收集评分中'), ('closed', '已截止'), ('finalized', '已归档')], default='collecting', max_length=15, verbose_name='状态')),
                ('trigger_source', models.CharField(choices=[('auto', 'Celery自动'), ('manual', '管理员手动')], default='manual', max_length=10, verbose_name='触发来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cycles', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '考核批次',
                'verbose_name_plural': '考核批次',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='JointStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('master', '硕士'), ('phd', '博士')], max_length=10, verbose_name='培养类型')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='学号')),
                ('enrollment_date', models.DateField(verbose_name='入学日期')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='毕业日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='在读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_joint_students', to='personnel.personnel', verbose_name='导师')),
                ('personnel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='joint_student', to='personnel.personnel', verbose_name='关联人员')),
            ],
            options={
                'verbose_name': '联培生',
                'verbose_name_plural': '联培生管理',
            },
        ),
        migrations.CreateModel(
            name='StipendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='平均分')),
                ('rank_in_cycle', models.PositiveSmallIntegerField(verbose_name='周期内排名')),
                ('grade', models.CharField(choices=[('A', 'A档'), ('B', 'B档')], max_length=1, verbose_name='档次')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基本额度')),
                ('grade_coefficient', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='档次系数')),
                ('attendance_ratio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='出勤比')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最终金额')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('locked', '已锁定')], default='pending', max_length=10, verbose_name='状态')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stipends', to='joint_students.assessmentcycle', verbose_name='考核批次')),
                ('joint_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stipends', to='joint_students.jointstudent', verbose_name='联培生')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_stipends', to=settings.AUTH_USER_MODEL, verbose_name='锁定操作人')),
            ],
            options={
                'verbose_name': '补助记录',
                'verbose_name_plural': '补助记录',
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年')),
                ('month', models.PositiveSmallIntegerField(verbose_name='月')),
                ('work_progress', models.TextField(verbose_name='工作进展')),
                ('work_highlights', models.TextField(verbose_name='工作亮点')),
                ('attendance_days_actual', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='实际出勤天数')),
                ('attendance_days_expected', models.DecimalField(decimal_places=1, default=22, max_digits=5, verbose_name='应出勤天数')),
                ('attendance_notes', models.TextField(blank=True, verbose_name='出勤说明')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已通过'), ('rejected', '已驳回')], default='draft', max_length=10, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('joint_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='joint_students.jointstudent', verbose_name='联培生')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '月度报告',
                'verbose_name_plural': '月度报告',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='ExpertScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='分数')),
                ('comment', models.TextField(blank=True, verbose_name='评语')),
                ('submitted_at', models.DateTimeField(verbose_name='提交时间')),
                ('is_locked', models.BooleanField(default=True, verbose_name='是否锁定')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='joint_students.assessmentcycle', verbose_name='考核批次')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expert_scores', to=settings.AUTH_USER_MODEL, verbose_name='专家')),
                ('joint_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expert_scores', to='joint_students.jointstudent', verbose_name='联培生')),
            ],
            options={
                'verbose_name': '专家打分',
                'verbose_name_plural': '专家打分',
            },
        ),
        migrations.AddConstraint(
            model_name='stipendrecord',
            constraint=models.UniqueConstraint(fields=('cycle', 'joint_student'), name='stipend_unique_per_cycle_student'),
        ),
        migrations.AddConstraint(
            model_name='monthlyreport',
            constraint=models.UniqueConstraint(fields=('joint_student', 'year', 'month'), name='report_unique_per_student_month'),
        ),
        migrations.AddIndex(
            model_name='jointstudent',
            index=models.Index(fields=['student_type', 'is_active'], name='js_type_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='expertscore',
            constraint=models.UniqueConstraint(fields=('cycle', 'expert', 'joint_student'), name='score_unique_per_expert_cycle_student'),
        ),
        migrations.AddConstraint(
            model_name='assessmentcycle',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='cycle_unique_per_month'),
        ),
    ]
