# Generated by Django 4.2.11 on 2026-01-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('不规范', '不规范'), ('时间冲突', '时间冲突'), ('内容缺失', '内容缺失'), ('内容与规定不符', '内容与规定不符'), ('其他', '其他')], max_length=50, verbose_name='问题类型')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='问题位置')),
                ('status', models.CharField(choices=[('待处理', '待处理'), ('处理中', '处理中'), ('已解决', '已解决'), ('已忽略', '已忽略')], default='待处理', max_length=50, verbose_name='处理状态')),
                ('severity', models.CharField(choices=[('低', '低'), ('中', '中'), ('高', '高'), ('紧急', '紧急')], default='中', max_length=50, verbose_name='严重程度')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '合规问题',
                'verbose_name_plural': '合规问题',
                'ordering': ['status', '-severity', 'due_date'],
            },
        ),
    ]
