# Generated by Django 4.2.11 on 2026-01-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceissue',
            name='document_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_issues', to='documents.book', verbose_name='关联书籍'),
        ),
        migrations.AddField(
            model_name='complianceissue',
            name='document_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_issues', to='documents.documenttemplate', verbose_name='关联文档模板'),
        ),
    ]
