# Generated by Django 4.2.11 on 2026-01-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('compliance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceissue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_issues', to='projects.project', verbose_name='所属项目'),
        ),
    ]
