# Generated by Django 4.2.30 on 2026-05-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceissue',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='complianceissue',
            name='status',
            field=models.CharField(choices=[('待处理', '待处理'), ('处理中', '处理中'), ('已解决', '已解决'), ('已忽略', '已忽略')], db_index=True, default='待处理', max_length=50, verbose_name='处理状态'),
        ),
    ]
