# Generated by Django 5.1.3 on 2025-08-17 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='会议室名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='容量')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='位置')),
            ],
            options={
                'verbose_name': '会议室',
                'verbose_name_plural': '会议室',
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('title', models.CharField(max_length=255, verbose_name='预约主题')),
                ('participants', models.TextField(blank=True, null=True, verbose_name='参与人员')),
                ('description', models.TextField(blank=True, null=True, verbose_name='预约描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('meeting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='meeting_rooms.meetingroom', verbose_name='会议室')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_bookings', to=settings.AUTH_USER_MODEL, verbose_name='预约用户')),
            ],
            options={
                'verbose_name': '会议室预约',
                'verbose_name_plural': '会议室预约',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='维护开始时间')),
                ('end_time', models.DateTimeField(verbose_name='维护结束时间')),
                ('reason', models.CharField(max_length=255, verbose_name='维护原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('meeting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_periods', to='meeting_rooms.meetingroom', verbose_name='会议室')),
            ],
            options={
                'verbose_name': '会议室维护',
                'verbose_name_plural': '会议室维护',
                'ordering': ['start_time'],
            },
        ),
    ]
