name: CI Tests

on:
  push:
    branches:
      - test

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('omni_desk_backend/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: ./omni_desk_backend
        run: pip install -r requirements-dev.txt

      - name: Run tests
        working-directory: ./omni_desk_backend
        env:
          PYTHONPATH: ${{ github.workspace }}
          DJANGO_SETTINGS_MODULE: omni_desk_backend.settings.test
        run: pytest --ds=omni_desk_backend.settings.test

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./omni_desk_frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: omni_desk_frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false
