name: Deploy to Windows Server via SSH

on:
  workflow_run:
    workflows: ["Run Tests, Build and Push Docker Images"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set "PROJECT_DIR=C:\projects\omni-desk"
            if not exist "%PROJECT_DIR%" (
              git clone https://github.com/${{ github.repository }}.git "%PROJECT_DIR%"
            )
            cd /d "%PROJECT_DIR%" && git pull && (echo BACKEND_IMAGE_TAG=${{ github.sha }} & echo FRONTEND_IMAGE_TAG=${{ github.sha }}) > .env && docker compose -f deployment/docker/docker-compose.prod.yml pull && docker compose -f deployment/docker/docker-compose.prod.yml up -d